# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnimationChannelData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'key_frames': 'list[KeyFrameData]',
        'pre': 'str',
        'post': 'str'
    }

    attribute_map = {
        'id': 'id',
        'key_frames': 'key_frames',
        'pre': 'pre',
        'post': 'post'
    }

    def __init__(self, id=None, key_frames=None, pre=None, post=None):  # noqa: E501
        """AnimationChannelData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._key_frames = None
        self._pre = None
        self._post = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if key_frames is not None:
            self.key_frames = key_frames
        if pre is not None:
            self.pre = pre
        if post is not None:
            self.post = post

    @property
    def id(self):
        """Gets the id of this AnimationChannelData.  # noqa: E501

        Name of the Animation channel  # noqa: E501

        :return: The id of this AnimationChannelData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AnimationChannelData.

        Name of the Animation channel  # noqa: E501

        :param id: The id of this AnimationChannelData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def key_frames(self):
        """Gets the key_frames of this AnimationChannelData.  # noqa: E501


        :return: The key_frames of this AnimationChannelData.  # noqa: E501
        :rtype: list[KeyFrameData]
        """
        return self._key_frames

    @key_frames.setter
    def key_frames(self, key_frames):
        """Sets the key_frames of this AnimationChannelData.


        :param key_frames: The key_frames of this AnimationChannelData.  # noqa: E501
        :type: list[KeyFrameData]
        """

        self._key_frames = key_frames

    @property
    def pre(self):
        """Gets the pre of this AnimationChannelData.  # noqa: E501

        Pre interpolation type \"C\" \"L\" \"P\" \"B\" constant, linear, loop, bounce  # noqa: E501

        :return: The pre of this AnimationChannelData.  # noqa: E501
        :rtype: str
        """
        return self._pre

    @pre.setter
    def pre(self, pre):
        """Sets the pre of this AnimationChannelData.

        Pre interpolation type \"C\" \"L\" \"P\" \"B\" constant, linear, loop, bounce  # noqa: E501

        :param pre: The pre of this AnimationChannelData.  # noqa: E501
        :type: str
        """

        self._pre = pre

    @property
    def post(self):
        """Gets the post of this AnimationChannelData.  # noqa: E501

        Post interpolation type \"C\" \"L\" \"P\" \"B\" constant, linear, loop, bounce  # noqa: E501

        :return: The post of this AnimationChannelData.  # noqa: E501
        :rtype: str
        """
        return self._post

    @post.setter
    def post(self, post):
        """Sets the post of this AnimationChannelData.

        Post interpolation type \"C\" \"L\" \"P\" \"B\" constant, linear, loop, bounce  # noqa: E501

        :param post: The post of this AnimationChannelData.  # noqa: E501
        :type: str
        """

        self._post = post

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnimationChannelData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnimationChannelData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
