# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApplicationData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mudule': 'str',
        'project': 'str',
        'position': 'str'
    }

    attribute_map = {
        'mudule': 'mudule',
        'project': 'project',
        'position': 'position'
    }

    def __init__(self, mudule=None, project=None, position=None):  # noqa: E501
        """ApplicationData - a model defined in Swagger"""  # noqa: E501
        self._mudule = None
        self._project = None
        self._position = None
        self.discriminator = None
        if mudule is not None:
            self.mudule = mudule
        if project is not None:
            self.project = project
        if position is not None:
            self.position = position

    @property
    def mudule(self):
        """Gets the mudule of this ApplicationData.  # noqa: E501

        Current active module (Start, Construct, Player)  # noqa: E501

        :return: The mudule of this ApplicationData.  # noqa: E501
        :rtype: str
        """
        return self._mudule

    @mudule.setter
    def mudule(self, mudule):
        """Sets the mudule of this ApplicationData.

        Current active module (Start, Construct, Player)  # noqa: E501

        :param mudule: The mudule of this ApplicationData.  # noqa: E501
        :type: str
        """

        self._mudule = mudule

    @property
    def project(self):
        """Gets the project of this ApplicationData.  # noqa: E501

        Current active project if any  # noqa: E501

        :return: The project of this ApplicationData.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this ApplicationData.

        Current active project if any  # noqa: E501

        :param project: The project of this ApplicationData.  # noqa: E501
        :type: str
        """

        self._project = project

    @property
    def position(self):
        """Gets the position of this ApplicationData.  # noqa: E501

        Current position in the player  # noqa: E501

        :return: The position of this ApplicationData.  # noqa: E501
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this ApplicationData.

        Current position in the player  # noqa: E501

        :param position: The position of this ApplicationData.  # noqa: E501
        :type: str
        """

        self._position = position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApplicationData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicationData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
