# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CameraData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'bool',
        'focal_length': 'float',
        'focus_distance': 'float',
        'sensor_width': 'float',
        'sensor_height': 'float',
        'sensor_crop': 'float',
        'bypass': 'bool',
        'position': 'CameraDataPosition',
        'offset': 'CameraDataOffset',
        'animation': 'AnimationData'
    }

    attribute_map = {
        'active': 'active',
        'focal_length': 'focal_length',
        'focus_distance': 'focus_distance',
        'sensor_width': 'sensor_width',
        'sensor_height': 'sensor_height',
        'sensor_crop': 'sensor_crop',
        'bypass': 'bypass',
        'position': 'position',
        'offset': 'offset',
        'animation': 'animation'
    }

    def __init__(self, active=None, focal_length=None, focus_distance=None, sensor_width=None, sensor_height=None, sensor_crop=None, bypass=None, position=None, offset=None, animation=None):  # noqa: E501
        """CameraData - a model defined in Swagger"""  # noqa: E501
        self._active = None
        self._focal_length = None
        self._focus_distance = None
        self._sensor_width = None
        self._sensor_height = None
        self._sensor_crop = None
        self._bypass = None
        self._position = None
        self._offset = None
        self._animation = None
        self.discriminator = None
        if active is not None:
            self.active = active
        if focal_length is not None:
            self.focal_length = focal_length
        if focus_distance is not None:
            self.focus_distance = focus_distance
        if sensor_width is not None:
            self.sensor_width = sensor_width
        if sensor_height is not None:
            self.sensor_height = sensor_height
        if sensor_crop is not None:
            self.sensor_crop = sensor_crop
        if bypass is not None:
            self.bypass = bypass
        if position is not None:
            self.position = position
        if offset is not None:
            self.offset = offset
        if animation is not None:
            self.animation = animation

    @property
    def active(self):
        """Gets the active of this CameraData.  # noqa: E501

        Activate / deactivate the camera  # noqa: E501

        :return: The active of this CameraData.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this CameraData.

        Activate / deactivate the camera  # noqa: E501

        :param active: The active of this CameraData.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def focal_length(self):
        """Gets the focal_length of this CameraData.  # noqa: E501

        Focal length / Zoom  # noqa: E501

        :return: The focal_length of this CameraData.  # noqa: E501
        :rtype: float
        """
        return self._focal_length

    @focal_length.setter
    def focal_length(self, focal_length):
        """Sets the focal_length of this CameraData.

        Focal length / Zoom  # noqa: E501

        :param focal_length: The focal_length of this CameraData.  # noqa: E501
        :type: float
        """

        self._focal_length = focal_length

    @property
    def focus_distance(self):
        """Gets the focus_distance of this CameraData.  # noqa: E501

        Focus distance  # noqa: E501

        :return: The focus_distance of this CameraData.  # noqa: E501
        :rtype: float
        """
        return self._focus_distance

    @focus_distance.setter
    def focus_distance(self, focus_distance):
        """Sets the focus_distance of this CameraData.

        Focus distance  # noqa: E501

        :param focus_distance: The focus_distance of this CameraData.  # noqa: E501
        :type: float
        """

        self._focus_distance = focus_distance

    @property
    def sensor_width(self):
        """Gets the sensor_width of this CameraData.  # noqa: E501

        Sensor width  # noqa: E501

        :return: The sensor_width of this CameraData.  # noqa: E501
        :rtype: float
        """
        return self._sensor_width

    @sensor_width.setter
    def sensor_width(self, sensor_width):
        """Sets the sensor_width of this CameraData.

        Sensor width  # noqa: E501

        :param sensor_width: The sensor_width of this CameraData.  # noqa: E501
        :type: float
        """

        self._sensor_width = sensor_width

    @property
    def sensor_height(self):
        """Gets the sensor_height of this CameraData.  # noqa: E501

        Sensor height  # noqa: E501

        :return: The sensor_height of this CameraData.  # noqa: E501
        :rtype: float
        """
        return self._sensor_height

    @sensor_height.setter
    def sensor_height(self, sensor_height):
        """Sets the sensor_height of this CameraData.

        Sensor height  # noqa: E501

        :param sensor_height: The sensor_height of this CameraData.  # noqa: E501
        :type: float
        """

        self._sensor_height = sensor_height

    @property
    def sensor_crop(self):
        """Gets the sensor_crop of this CameraData.  # noqa: E501

        Sensor crop  # noqa: E501

        :return: The sensor_crop of this CameraData.  # noqa: E501
        :rtype: float
        """
        return self._sensor_crop

    @sensor_crop.setter
    def sensor_crop(self, sensor_crop):
        """Sets the sensor_crop of this CameraData.

        Sensor crop  # noqa: E501

        :param sensor_crop: The sensor_crop of this CameraData.  # noqa: E501
        :type: float
        """

        self._sensor_crop = sensor_crop

    @property
    def bypass(self):
        """Gets the bypass of this CameraData.  # noqa: E501

        By-pass the camera translation and rotation for rendering  # noqa: E501

        :return: The bypass of this CameraData.  # noqa: E501
        :rtype: bool
        """
        return self._bypass

    @bypass.setter
    def bypass(self, bypass):
        """Sets the bypass of this CameraData.

        By-pass the camera translation and rotation for rendering  # noqa: E501

        :param bypass: The bypass of this CameraData.  # noqa: E501
        :type: bool
        """

        self._bypass = bypass

    @property
    def position(self):
        """Gets the position of this CameraData.  # noqa: E501


        :return: The position of this CameraData.  # noqa: E501
        :rtype: CameraDataPosition
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this CameraData.


        :param position: The position of this CameraData.  # noqa: E501
        :type: CameraDataPosition
        """

        self._position = position

    @property
    def offset(self):
        """Gets the offset of this CameraData.  # noqa: E501


        :return: The offset of this CameraData.  # noqa: E501
        :rtype: CameraDataOffset
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this CameraData.


        :param offset: The offset of this CameraData.  # noqa: E501
        :type: CameraDataOffset
        """

        self._offset = offset

    @property
    def animation(self):
        """Gets the animation of this CameraData.  # noqa: E501


        :return: The animation of this CameraData.  # noqa: E501
        :rtype: AnimationData
        """
        return self._animation

    @animation.setter
    def animation(self, animation):
        """Sets the animation of this CameraData.


        :param animation: The animation of this CameraData.  # noqa: E501
        :type: AnimationData
        """

        self._animation = animation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CameraData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CameraData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
