# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CameraDataOffset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tx': 'float',
        'ty': 'float',
        'tz': 'float',
        'rx': 'float',
        'ry': 'float',
        'rz': 'float'
    }

    attribute_map = {
        'tx': 'tx',
        'ty': 'ty',
        'tz': 'tz',
        'rx': 'rx',
        'ry': 'ry',
        'rz': 'rz'
    }

    def __init__(self, tx=None, ty=None, tz=None, rx=None, ry=None, rz=None):  # noqa: E501
        """CameraDataOffset - a model defined in Swagger"""  # noqa: E501
        self._tx = None
        self._ty = None
        self._tz = None
        self._rx = None
        self._ry = None
        self._rz = None
        self.discriminator = None
        if tx is not None:
            self.tx = tx
        if ty is not None:
            self.ty = ty
        if tz is not None:
            self.tz = tz
        if rx is not None:
            self.rx = rx
        if ry is not None:
            self.ry = ry
        if rz is not None:
            self.rz = rz

    @property
    def tx(self):
        """Gets the tx of this CameraDataOffset.  # noqa: E501

        Translation X  # noqa: E501

        :return: The tx of this CameraDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._tx

    @tx.setter
    def tx(self, tx):
        """Sets the tx of this CameraDataOffset.

        Translation X  # noqa: E501

        :param tx: The tx of this CameraDataOffset.  # noqa: E501
        :type: float
        """

        self._tx = tx

    @property
    def ty(self):
        """Gets the ty of this CameraDataOffset.  # noqa: E501

        Translation Y  # noqa: E501

        :return: The ty of this CameraDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._ty

    @ty.setter
    def ty(self, ty):
        """Sets the ty of this CameraDataOffset.

        Translation Y  # noqa: E501

        :param ty: The ty of this CameraDataOffset.  # noqa: E501
        :type: float
        """

        self._ty = ty

    @property
    def tz(self):
        """Gets the tz of this CameraDataOffset.  # noqa: E501

        Translation Z  # noqa: E501

        :return: The tz of this CameraDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._tz

    @tz.setter
    def tz(self, tz):
        """Sets the tz of this CameraDataOffset.

        Translation Z  # noqa: E501

        :param tz: The tz of this CameraDataOffset.  # noqa: E501
        :type: float
        """

        self._tz = tz

    @property
    def rx(self):
        """Gets the rx of this CameraDataOffset.  # noqa: E501

        Rotation X  # noqa: E501

        :return: The rx of this CameraDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._rx

    @rx.setter
    def rx(self, rx):
        """Sets the rx of this CameraDataOffset.

        Rotation X  # noqa: E501

        :param rx: The rx of this CameraDataOffset.  # noqa: E501
        :type: float
        """

        self._rx = rx

    @property
    def ry(self):
        """Gets the ry of this CameraDataOffset.  # noqa: E501

        Rotation Y  # noqa: E501

        :return: The ry of this CameraDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._ry

    @ry.setter
    def ry(self, ry):
        """Sets the ry of this CameraDataOffset.

        Rotation Y  # noqa: E501

        :param ry: The ry of this CameraDataOffset.  # noqa: E501
        :type: float
        """

        self._ry = ry

    @property
    def rz(self):
        """Gets the rz of this CameraDataOffset.  # noqa: E501


        :return: The rz of this CameraDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._rz

    @rz.setter
    def rz(self, rz):
        """Sets the rz of this CameraDataOffset.


        :param rz: The rz of this CameraDataOffset.  # noqa: E501
        :type: float
        """

        self._rz = rz

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CameraDataOffset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CameraDataOffset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
