# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ColorgradeDataColorb(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'h': 'float',
        'l': 'float',
        's': 'float'
    }

    attribute_map = {
        'h': 'h',
        'l': 'l',
        's': 's'
    }

    def __init__(self, h=None, l=None, s=None):  # noqa: E501
        """ColorgradeDataColorb - a model defined in Swagger"""  # noqa: E501
        self._h = None
        self._l = None
        self._s = None
        self.discriminator = None
        if h is not None:
            self.h = h
        if l is not None:
            self.l = l
        if s is not None:
            self.s = s

    @property
    def h(self):
        """Gets the h of this ColorgradeDataColorb.  # noqa: E501

        Hue  # noqa: E501

        :return: The h of this ColorgradeDataColorb.  # noqa: E501
        :rtype: float
        """
        return self._h

    @h.setter
    def h(self, h):
        """Sets the h of this ColorgradeDataColorb.

        Hue  # noqa: E501

        :param h: The h of this ColorgradeDataColorb.  # noqa: E501
        :type: float
        """

        self._h = h

    @property
    def l(self):
        """Gets the l of this ColorgradeDataColorb.  # noqa: E501

        Brightness  # noqa: E501

        :return: The l of this ColorgradeDataColorb.  # noqa: E501
        :rtype: float
        """
        return self._l

    @l.setter
    def l(self, l):
        """Sets the l of this ColorgradeDataColorb.

        Brightness  # noqa: E501

        :param l: The l of this ColorgradeDataColorb.  # noqa: E501
        :type: float
        """

        self._l = l

    @property
    def s(self):
        """Gets the s of this ColorgradeDataColorb.  # noqa: E501

        Saturation  # noqa: E501

        :return: The s of this ColorgradeDataColorb.  # noqa: E501
        :rtype: float
        """
        return self._s

    @s.setter
    def s(self, s):
        """Sets the s of this ColorgradeDataColorb.

        Saturation  # noqa: E501

        :param s: The s of this ColorgradeDataColorb.  # noqa: E501
        :type: float
        """

        self._s = s

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ColorgradeDataColorb, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ColorgradeDataColorb):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
