# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ColorgradeData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'offset': 'ColorgradeDataOffset',
        'pre_gain': 'ColorgradeDataPreGain',
        'color_a': 'ColorgradeDataColora',
        'lift': 'ColorgradeDataLift',
        'gamma': 'ColorgradeDataGamma',
        'gain': 'ColorgradeDataGain',
        'color_b': 'ColorgradeDataColorb',
        'tone': 'ColorgradeDataTone',
        'temperature': 'ColorgradeDataTemperature',
        'aperature': 'Aperature',
        'noise': 'float',
        'channel_invert': 'bool',
        'channel_remap': 'str',
        'soft_clip_high': 'ColorgradeDataSoftClipHigh',
        'soft_clip_low': 'ColorgradeDataSoftClipLow',
        'clip_high': 'ColorgradeDataClipHigh',
        'clip_low': 'ColorgradeDataClipLow',
        'lut': 'str'
    }

    attribute_map = {
        'offset': 'offset',
        'pre_gain': 'pre_gain',
        'color_a': 'color-a',
        'lift': 'lift',
        'gamma': 'gamma',
        'gain': 'gain',
        'color_b': 'color-b',
        'tone': 'tone',
        'temperature': 'temperature',
        'aperature': 'aperature',
        'noise': 'noise',
        'channel_invert': 'channel_invert',
        'channel_remap': 'channel_remap',
        'soft_clip_high': 'soft_clip_high',
        'soft_clip_low': 'soft_clip_low',
        'clip_high': 'clip_high',
        'clip_low': 'clip_low',
        'lut': 'lut'
    }

    def __init__(self, offset=None, pre_gain=None, color_a=None, lift=None, gamma=None, gain=None, color_b=None, tone=None, temperature=None, aperature=None, noise=None, channel_invert=None, channel_remap=None, soft_clip_high=None, soft_clip_low=None, clip_high=None, clip_low=None, lut=None):  # noqa: E501
        """ColorgradeData - a model defined in Swagger"""  # noqa: E501
        self._offset = None
        self._pre_gain = None
        self._color_a = None
        self._lift = None
        self._gamma = None
        self._gain = None
        self._color_b = None
        self._tone = None
        self._temperature = None
        self._aperature = None
        self._noise = None
        self._channel_invert = None
        self._channel_remap = None
        self._soft_clip_high = None
        self._soft_clip_low = None
        self._clip_high = None
        self._clip_low = None
        self._lut = None
        self.discriminator = None
        if offset is not None:
            self.offset = offset
        if pre_gain is not None:
            self.pre_gain = pre_gain
        if color_a is not None:
            self.color_a = color_a
        if lift is not None:
            self.lift = lift
        if gamma is not None:
            self.gamma = gamma
        if gain is not None:
            self.gain = gain
        if color_b is not None:
            self.color_b = color_b
        if tone is not None:
            self.tone = tone
        if temperature is not None:
            self.temperature = temperature
        if aperature is not None:
            self.aperature = aperature
        if noise is not None:
            self.noise = noise
        if channel_invert is not None:
            self.channel_invert = channel_invert
        if channel_remap is not None:
            self.channel_remap = channel_remap
        if soft_clip_high is not None:
            self.soft_clip_high = soft_clip_high
        if soft_clip_low is not None:
            self.soft_clip_low = soft_clip_low
        if clip_high is not None:
            self.clip_high = clip_high
        if clip_low is not None:
            self.clip_low = clip_low
        if lut is not None:
            self.lut = lut

    @property
    def offset(self):
        """Gets the offset of this ColorgradeData.  # noqa: E501


        :return: The offset of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataOffset
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this ColorgradeData.


        :param offset: The offset of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataOffset
        """

        self._offset = offset

    @property
    def pre_gain(self):
        """Gets the pre_gain of this ColorgradeData.  # noqa: E501


        :return: The pre_gain of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataPreGain
        """
        return self._pre_gain

    @pre_gain.setter
    def pre_gain(self, pre_gain):
        """Sets the pre_gain of this ColorgradeData.


        :param pre_gain: The pre_gain of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataPreGain
        """

        self._pre_gain = pre_gain

    @property
    def color_a(self):
        """Gets the color_a of this ColorgradeData.  # noqa: E501


        :return: The color_a of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataColora
        """
        return self._color_a

    @color_a.setter
    def color_a(self, color_a):
        """Sets the color_a of this ColorgradeData.


        :param color_a: The color_a of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataColora
        """

        self._color_a = color_a

    @property
    def lift(self):
        """Gets the lift of this ColorgradeData.  # noqa: E501


        :return: The lift of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataLift
        """
        return self._lift

    @lift.setter
    def lift(self, lift):
        """Sets the lift of this ColorgradeData.


        :param lift: The lift of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataLift
        """

        self._lift = lift

    @property
    def gamma(self):
        """Gets the gamma of this ColorgradeData.  # noqa: E501


        :return: The gamma of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataGamma
        """
        return self._gamma

    @gamma.setter
    def gamma(self, gamma):
        """Sets the gamma of this ColorgradeData.


        :param gamma: The gamma of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataGamma
        """

        self._gamma = gamma

    @property
    def gain(self):
        """Gets the gain of this ColorgradeData.  # noqa: E501


        :return: The gain of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataGain
        """
        return self._gain

    @gain.setter
    def gain(self, gain):
        """Sets the gain of this ColorgradeData.


        :param gain: The gain of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataGain
        """

        self._gain = gain

    @property
    def color_b(self):
        """Gets the color_b of this ColorgradeData.  # noqa: E501


        :return: The color_b of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataColorb
        """
        return self._color_b

    @color_b.setter
    def color_b(self, color_b):
        """Sets the color_b of this ColorgradeData.


        :param color_b: The color_b of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataColorb
        """

        self._color_b = color_b

    @property
    def tone(self):
        """Gets the tone of this ColorgradeData.  # noqa: E501


        :return: The tone of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataTone
        """
        return self._tone

    @tone.setter
    def tone(self, tone):
        """Sets the tone of this ColorgradeData.


        :param tone: The tone of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataTone
        """

        self._tone = tone

    @property
    def temperature(self):
        """Gets the temperature of this ColorgradeData.  # noqa: E501


        :return: The temperature of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataTemperature
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this ColorgradeData.


        :param temperature: The temperature of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataTemperature
        """

        self._temperature = temperature

    @property
    def aperature(self):
        """Gets the aperature of this ColorgradeData.  # noqa: E501


        :return: The aperature of this ColorgradeData.  # noqa: E501
        :rtype: Aperature
        """
        return self._aperature

    @aperature.setter
    def aperature(self, aperature):
        """Sets the aperature of this ColorgradeData.


        :param aperature: The aperature of this ColorgradeData.  # noqa: E501
        :type: Aperature
        """

        self._aperature = aperature

    @property
    def noise(self):
        """Gets the noise of this ColorgradeData.  # noqa: E501

        Amount of noise to add to the shot  # noqa: E501

        :return: The noise of this ColorgradeData.  # noqa: E501
        :rtype: float
        """
        return self._noise

    @noise.setter
    def noise(self, noise):
        """Sets the noise of this ColorgradeData.

        Amount of noise to add to the shot  # noqa: E501

        :param noise: The noise of this ColorgradeData.  # noqa: E501
        :type: float
        """

        self._noise = noise

    @property
    def channel_invert(self):
        """Gets the channel_invert of this ColorgradeData.  # noqa: E501

        Whether to invert the color channels  # noqa: E501

        :return: The channel_invert of this ColorgradeData.  # noqa: E501
        :rtype: bool
        """
        return self._channel_invert

    @channel_invert.setter
    def channel_invert(self, channel_invert):
        """Sets the channel_invert of this ColorgradeData.

        Whether to invert the color channels  # noqa: E501

        :param channel_invert: The channel_invert of this ColorgradeData.  # noqa: E501
        :type: bool
        """

        self._channel_invert = channel_invert

    @property
    def channel_remap(self):
        """Gets the channel_remap of this ColorgradeData.  # noqa: E501

        Remapping of color channels  # noqa: E501

        :return: The channel_remap of this ColorgradeData.  # noqa: E501
        :rtype: str
        """
        return self._channel_remap

    @channel_remap.setter
    def channel_remap(self, channel_remap):
        """Sets the channel_remap of this ColorgradeData.

        Remapping of color channels  # noqa: E501

        :param channel_remap: The channel_remap of this ColorgradeData.  # noqa: E501
        :type: str
        """

        self._channel_remap = channel_remap

    @property
    def soft_clip_high(self):
        """Gets the soft_clip_high of this ColorgradeData.  # noqa: E501


        :return: The soft_clip_high of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataSoftClipHigh
        """
        return self._soft_clip_high

    @soft_clip_high.setter
    def soft_clip_high(self, soft_clip_high):
        """Sets the soft_clip_high of this ColorgradeData.


        :param soft_clip_high: The soft_clip_high of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataSoftClipHigh
        """

        self._soft_clip_high = soft_clip_high

    @property
    def soft_clip_low(self):
        """Gets the soft_clip_low of this ColorgradeData.  # noqa: E501


        :return: The soft_clip_low of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataSoftClipLow
        """
        return self._soft_clip_low

    @soft_clip_low.setter
    def soft_clip_low(self, soft_clip_low):
        """Sets the soft_clip_low of this ColorgradeData.


        :param soft_clip_low: The soft_clip_low of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataSoftClipLow
        """

        self._soft_clip_low = soft_clip_low

    @property
    def clip_high(self):
        """Gets the clip_high of this ColorgradeData.  # noqa: E501


        :return: The clip_high of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataClipHigh
        """
        return self._clip_high

    @clip_high.setter
    def clip_high(self, clip_high):
        """Sets the clip_high of this ColorgradeData.


        :param clip_high: The clip_high of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataClipHigh
        """

        self._clip_high = clip_high

    @property
    def clip_low(self):
        """Gets the clip_low of this ColorgradeData.  # noqa: E501


        :return: The clip_low of this ColorgradeData.  # noqa: E501
        :rtype: ColorgradeDataClipLow
        """
        return self._clip_low

    @clip_low.setter
    def clip_low(self, clip_low):
        """Sets the clip_low of this ColorgradeData.


        :param clip_low: The clip_low of this ColorgradeData.  # noqa: E501
        :type: ColorgradeDataClipLow
        """

        self._clip_low = clip_low

    @property
    def lut(self):
        """Gets the lut of this ColorgradeData.  # noqa: E501

        LUT applied to the colorgrade  # noqa: E501

        :return: The lut of this ColorgradeData.  # noqa: E501
        :rtype: str
        """
        return self._lut

    @lut.setter
    def lut(self, lut):
        """Sets the lut of this ColorgradeData.

        LUT applied to the colorgrade  # noqa: E501

        :param lut: The lut of this ColorgradeData.  # noqa: E501
        :type: str
        """

        self._lut = lut

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ColorgradeData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ColorgradeData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
