# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ColorgradeDataTemperature(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'k': 'float',
        't': 'float'
    }

    attribute_map = {
        'k': 'k',
        't': 't'
    }

    def __init__(self, k=None, t=None):  # noqa: E501
        """ColorgradeDataTemperature - a model defined in Swagger"""  # noqa: E501
        self._k = None
        self._t = None
        self.discriminator = None
        if k is not None:
            self.k = k
        if t is not None:
            self.t = t

    @property
    def k(self):
        """Gets the k of this ColorgradeDataTemperature.  # noqa: E501

        Kelvin temperature  # noqa: E501

        :return: The k of this ColorgradeDataTemperature.  # noqa: E501
        :rtype: float
        """
        return self._k

    @k.setter
    def k(self, k):
        """Sets the k of this ColorgradeDataTemperature.

        Kelvin temperature  # noqa: E501

        :param k: The k of this ColorgradeDataTemperature.  # noqa: E501
        :type: float
        """

        self._k = k

    @property
    def t(self):
        """Gets the t of this ColorgradeDataTemperature.  # noqa: E501

        Tint  # noqa: E501

        :return: The t of this ColorgradeDataTemperature.  # noqa: E501
        :rtype: float
        """
        return self._t

    @t.setter
    def t(self, t):
        """Sets the t of this ColorgradeDataTemperature.

        Tint  # noqa: E501

        :param t: The t of this ColorgradeDataTemperature.  # noqa: E501
        :type: float
        """

        self._t = t

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ColorgradeDataTemperature, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ColorgradeDataTemperature):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
