# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ColorgradeDataOffset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'b': 'float',
        'g': 'float',
        'm': 'float',
        'r': 'float'
    }

    attribute_map = {
        'b': 'b',
        'g': 'g',
        'm': 'm',
        'r': 'r'
    }

    def __init__(self, b=None, g=None, m=None, r=None):  # noqa: E501
        """ColorgradeDataOffset - a model defined in Swagger"""  # noqa: E501
        self._b = None
        self._g = None
        self._m = None
        self._r = None
        self.discriminator = None
        if b is not None:
            self.b = b
        if g is not None:
            self.g = g
        if m is not None:
            self.m = m
        if r is not None:
            self.r = r

    @property
    def b(self):
        """Gets the b of this ColorgradeDataOffset.  # noqa: E501

        Blue channel offset  # noqa: E501

        :return: The b of this ColorgradeDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._b

    @b.setter
    def b(self, b):
        """Sets the b of this ColorgradeDataOffset.

        Blue channel offset  # noqa: E501

        :param b: The b of this ColorgradeDataOffset.  # noqa: E501
        :type: float
        """

        self._b = b

    @property
    def g(self):
        """Gets the g of this ColorgradeDataOffset.  # noqa: E501

        Green channel offset  # noqa: E501

        :return: The g of this ColorgradeDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._g

    @g.setter
    def g(self, g):
        """Sets the g of this ColorgradeDataOffset.

        Green channel offset  # noqa: E501

        :param g: The g of this ColorgradeDataOffset.  # noqa: E501
        :type: float
        """

        self._g = g

    @property
    def m(self):
        """Gets the m of this ColorgradeDataOffset.  # noqa: E501

        Master offset  # noqa: E501

        :return: The m of this ColorgradeDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._m

    @m.setter
    def m(self, m):
        """Sets the m of this ColorgradeDataOffset.

        Master offset  # noqa: E501

        :param m: The m of this ColorgradeDataOffset.  # noqa: E501
        :type: float
        """

        self._m = m

    @property
    def r(self):
        """Gets the r of this ColorgradeDataOffset.  # noqa: E501

        Red channel offset  # noqa: E501

        :return: The r of this ColorgradeDataOffset.  # noqa: E501
        :rtype: float
        """
        return self._r

    @r.setter
    def r(self, r):
        """Sets the r of this ColorgradeDataOffset.

        Red channel offset  # noqa: E501

        :param r: The r of this ColorgradeDataOffset.  # noqa: E501
        :type: float
        """

        self._r = r

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ColorgradeDataOffset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ColorgradeDataOffset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
