# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Colorspace(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ACES_AP0_ = "ACES (AP0)"
    ACESCG_AP1_ = "ACEScg (AP1)"
    ADOBE_RGB_1998_ = "Adobe RGB (1998)"
    ADOBE_WIDE_GAMUT = "Adobe Wide Gamut"
    APPLE_WIDE_GAMUT = "Apple Wide Gamut"
    ARRI_WIDE_GAMUT_3 = "ARRI Wide Gamut 3"
    ARRI_WIDE_GAMUT_4 = "ARRI Wide Gamut 4"
    BLACKMAGIC_DWG = "Blackmagic DWG"
    BMD_WIDE_GAMUT = "BMD Wide Gamut"
    CANON_CINEMA_GAMUT = "Canon Cinema Gamut"
    DCI_XYZ = "DCI XYZ"
    DJI_D_GAMUT = "DJI D-Gamut"
    FUJIFILM_F_GAMUT_C = "Fujifilm F-Gamut C"
    P3_D60 = "P3 D60"
    P3_D65 = "P3 D65"
    P3_DCI = "P3 DCI"
    PANASONIC_V_GAMUT = "Panasonic V-Gamut"
    REC2020 = "Rec2020"
    REC709 = "Rec709"
    RED_WIDE_GAMUT = "RED Wide Gamut"
    SONY_S_GAMUT3 = "Sony S-Gamut3"
    SONY_S_GAMUT3_CINE = "Sony S-Gamut3 Cine"
    SRGB = "sRGB"
    XYZ = "XYZ"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """Colorspace - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Colorspace, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Colorspace):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
