# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ColorgradeDataTone(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'c': 'float',
        'i': 'float',
        's': 'float'
    }

    attribute_map = {
        'c': 'c',
        'i': 'i',
        's': 's'
    }

    def __init__(self, c=None, i=None, s=None):  # noqa: E501
        """ColorgradeDataTone - a model defined in Swagger"""  # noqa: E501
        self._c = None
        self._i = None
        self._s = None
        self.discriminator = None
        if c is not None:
            self.c = c
        if i is not None:
            self.i = i
        if s is not None:
            self.s = s

    @property
    def c(self):
        """Gets the c of this ColorgradeDataTone.  # noqa: E501

        Contrast  # noqa: E501

        :return: The c of this ColorgradeDataTone.  # noqa: E501
        :rtype: float
        """
        return self._c

    @c.setter
    def c(self, c):
        """Sets the c of this ColorgradeDataTone.

        Contrast  # noqa: E501

        :param c: The c of this ColorgradeDataTone.  # noqa: E501
        :type: float
        """

        self._c = c

    @property
    def i(self):
        """Gets the i of this ColorgradeDataTone.  # noqa: E501

        ISO Gain  # noqa: E501

        :return: The i of this ColorgradeDataTone.  # noqa: E501
        :rtype: float
        """
        return self._i

    @i.setter
    def i(self, i):
        """Sets the i of this ColorgradeDataTone.

        ISO Gain  # noqa: E501

        :param i: The i of this ColorgradeDataTone.  # noqa: E501
        :type: float
        """

        self._i = i

    @property
    def s(self):
        """Gets the s of this ColorgradeDataTone.  # noqa: E501

        S Curve  # noqa: E501

        :return: The s of this ColorgradeDataTone.  # noqa: E501
        :rtype: float
        """
        return self._s

    @s.setter
    def s(self, s):
        """Sets the s of this ColorgradeDataTone.

        S Curve  # noqa: E501

        :param s: The s of this ColorgradeDataTone.  # noqa: E501
        :type: float
        """

        self._s = s

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ColorgradeDataTone, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ColorgradeDataTone):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
