# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConstructData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fps': 'float',
        'name': 'str',
        'notes': 'list[NoteData]',
        'parent': 'Uuid',
        'record_tc': 'Timecode',
        'resolution': 'ConstructDataResolution',
        'aspect': 'float',
        'uuid': 'Uuid',
        'audio': 'ConstructDataAudio',
        'slots': 'list[SlotData]'
    }

    attribute_map = {
        'fps': 'fps',
        'name': 'name',
        'notes': 'notes',
        'parent': 'parent',
        'record_tc': 'record_tc',
        'resolution': 'resolution',
        'aspect': 'aspect',
        'uuid': 'uuid',
        'audio': 'audio',
        'slots': 'slots'
    }

    def __init__(self, fps=None, name=None, notes=None, parent=None, record_tc=None, resolution=None, aspect=None, uuid=None, audio=None, slots=None):  # noqa: E501
        """ConstructData - a model defined in Swagger"""  # noqa: E501
        self._fps = None
        self._name = None
        self._notes = None
        self._parent = None
        self._record_tc = None
        self._resolution = None
        self._aspect = None
        self._uuid = None
        self._audio = None
        self._slots = None
        self.discriminator = None
        if fps is not None:
            self.fps = fps
        self.name = name
        if notes is not None:
            self.notes = notes
        if parent is not None:
            self.parent = parent
        if record_tc is not None:
            self.record_tc = record_tc
        if resolution is not None:
            self.resolution = resolution
        if aspect is not None:
            self.aspect = aspect
        self.uuid = uuid
        if audio is not None:
            self.audio = audio
        if slots is not None:
            self.slots = slots

    @property
    def fps(self):
        """Gets the fps of this ConstructData.  # noqa: E501

        Frames per second of the Construct output  # noqa: E501

        :return: The fps of this ConstructData.  # noqa: E501
        :rtype: float
        """
        return self._fps

    @fps.setter
    def fps(self, fps):
        """Sets the fps of this ConstructData.

        Frames per second of the Construct output  # noqa: E501

        :param fps: The fps of this ConstructData.  # noqa: E501
        :type: float
        """

        self._fps = fps

    @property
    def name(self):
        """Gets the name of this ConstructData.  # noqa: E501

        Name of the Construct  # noqa: E501

        :return: The name of this ConstructData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConstructData.

        Name of the Construct  # noqa: E501

        :param name: The name of this ConstructData.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def notes(self):
        """Gets the notes of this ConstructData.  # noqa: E501

        Notes of the Construct  # noqa: E501

        :return: The notes of this ConstructData.  # noqa: E501
        :rtype: list[NoteData]
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this ConstructData.

        Notes of the Construct  # noqa: E501

        :param notes: The notes of this ConstructData.  # noqa: E501
        :type: list[NoteData]
        """

        self._notes = notes

    @property
    def parent(self):
        """Gets the parent of this ConstructData.  # noqa: E501


        :return: The parent of this ConstructData.  # noqa: E501
        :rtype: Uuid
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this ConstructData.


        :param parent: The parent of this ConstructData.  # noqa: E501
        :type: Uuid
        """

        self._parent = parent

    @property
    def record_tc(self):
        """Gets the record_tc of this ConstructData.  # noqa: E501


        :return: The record_tc of this ConstructData.  # noqa: E501
        :rtype: Timecode
        """
        return self._record_tc

    @record_tc.setter
    def record_tc(self, record_tc):
        """Sets the record_tc of this ConstructData.


        :param record_tc: The record_tc of this ConstructData.  # noqa: E501
        :type: Timecode
        """

        self._record_tc = record_tc

    @property
    def resolution(self):
        """Gets the resolution of this ConstructData.  # noqa: E501


        :return: The resolution of this ConstructData.  # noqa: E501
        :rtype: ConstructDataResolution
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution):
        """Sets the resolution of this ConstructData.


        :param resolution: The resolution of this ConstructData.  # noqa: E501
        :type: ConstructDataResolution
        """

        self._resolution = resolution

    @property
    def aspect(self):
        """Gets the aspect of this ConstructData.  # noqa: E501

        Aspect ratio of the Construct output  # noqa: E501

        :return: The aspect of this ConstructData.  # noqa: E501
        :rtype: float
        """
        return self._aspect

    @aspect.setter
    def aspect(self, aspect):
        """Sets the aspect of this ConstructData.

        Aspect ratio of the Construct output  # noqa: E501

        :param aspect: The aspect of this ConstructData.  # noqa: E501
        :type: float
        """

        self._aspect = aspect

    @property
    def uuid(self):
        """Gets the uuid of this ConstructData.  # noqa: E501


        :return: The uuid of this ConstructData.  # noqa: E501
        :rtype: Uuid
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ConstructData.


        :param uuid: The uuid of this ConstructData.  # noqa: E501
        :type: Uuid
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def audio(self):
        """Gets the audio of this ConstructData.  # noqa: E501


        :return: The audio of this ConstructData.  # noqa: E501
        :rtype: ConstructDataAudio
        """
        return self._audio

    @audio.setter
    def audio(self, audio):
        """Sets the audio of this ConstructData.


        :param audio: The audio of this ConstructData.  # noqa: E501
        :type: ConstructDataAudio
        """

        self._audio = audio

    @property
    def slots(self):
        """Gets the slots of this ConstructData.  # noqa: E501

        List of Slots of the Construct (only included with level set to ALL)  # noqa: E501

        :return: The slots of this ConstructData.  # noqa: E501
        :rtype: list[SlotData]
        """
        return self._slots

    @slots.setter
    def slots(self, slots):
        """Sets the slots of this ConstructData.

        List of Slots of the Construct (only included with level set to ALL)  # noqa: E501

        :param slots: The slots of this ConstructData.  # noqa: E501
        :type: list[SlotData]
        """

        self._slots = slots

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConstructData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConstructData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
