# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Eotf(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ACESCC = "ACEScc"
    ACESCCT = "ACEScct"
    APPLE_LOG = "Apple Log"
    ARRI_LOGC3 = "ARRI LogC3"
    ARRI_LOGC4 = "ARRI LogC4"
    BLACKMAGIC_DI = "Blackmagic DI"
    BMD_FILM = "BMD Film"
    BMD_FILM_GEN_5 = "BMD Film Gen 5"
    CANON_LOG2 = "Canon Log2"
    CANON_LOG3 = "Canon Log3"
    CINEON_LOG = "Cineon Log"
    DJI_D_LOG = "DJI D-Log"
    FUJIFILM_F_LOG = "Fujifilm F-Log"
    FUJIFILM_F_LOG2 = "Fujifilm F-Log2"
    GAMMA_2_2 = "Gamma 2.2"
    GAMMA_2_4 = "Gamma 2.4"
    GAMMA_2_6_DCI_ = "Gamma 2.6 (DCI)"
    HLG_HDR = "HLG HDR"
    HLG_SCENE_HDR = "HLG Scene HDR"
    LEICA_L_LOG = "Leica L-Log"
    NIKON_N_LOG = "Nikon N-Log"
    PANASONIC_V_LOG = "Panasonic V-Log"
    PQ_HDR = "PQ HDR"
    RED_LOG3G10 = "RED Log3G10"
    SCENE_LINEAR = "Scene Linear"
    SONY_S_LOG2 = "Sony S-Log2"
    SONY_S_LOG3 = "Sony S-Log3"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """Eotf - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Eotf, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Eotf):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
