# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'bool',
        'name': 'str',
        'notes': 'list[NoteData]',
        'uuid': 'Uuid',
        'constructs': 'list[ConstructData]'
    }

    attribute_map = {
        'active': 'active',
        'name': 'name',
        'notes': 'notes',
        'uuid': 'uuid',
        'constructs': 'constructs'
    }

    def __init__(self, active=None, name=None, notes=None, uuid=None, constructs=None):  # noqa: E501
        """GroupData - a model defined in Swagger"""  # noqa: E501
        self._active = None
        self._name = None
        self._notes = None
        self._uuid = None
        self._constructs = None
        self.discriminator = None
        if active is not None:
            self.active = active
        self.name = name
        if notes is not None:
            self.notes = notes
        self.uuid = uuid
        if constructs is not None:
            self.constructs = constructs

    @property
    def active(self):
        """Gets the active of this GroupData.  # noqa: E501

        Is the Group the active group  # noqa: E501

        :return: The active of this GroupData.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this GroupData.

        Is the Group the active group  # noqa: E501

        :param active: The active of this GroupData.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def name(self):
        """Gets the name of this GroupData.  # noqa: E501

        Name of the Group  # noqa: E501

        :return: The name of this GroupData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GroupData.

        Name of the Group  # noqa: E501

        :param name: The name of this GroupData.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def notes(self):
        """Gets the notes of this GroupData.  # noqa: E501

        Notes of the Group  # noqa: E501

        :return: The notes of this GroupData.  # noqa: E501
        :rtype: list[NoteData]
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this GroupData.

        Notes of the Group  # noqa: E501

        :param notes: The notes of this GroupData.  # noqa: E501
        :type: list[NoteData]
        """

        self._notes = notes

    @property
    def uuid(self):
        """Gets the uuid of this GroupData.  # noqa: E501


        :return: The uuid of this GroupData.  # noqa: E501
        :rtype: Uuid
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this GroupData.


        :param uuid: The uuid of this GroupData.  # noqa: E501
        :type: Uuid
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def constructs(self):
        """Gets the constructs of this GroupData.  # noqa: E501

        List of Constructs in the Group  # noqa: E501

        :return: The constructs of this GroupData.  # noqa: E501
        :rtype: list[ConstructData]
        """
        return self._constructs

    @constructs.setter
    def constructs(self, constructs):
        """Sets the constructs of this GroupData.

        List of Constructs in the Group  # noqa: E501

        :param constructs: The constructs of this GroupData.  # noqa: E501
        :type: list[ConstructData]
        """

        self._constructs = constructs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
