# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InputData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grade': 'bool',
        'input_uuid': 'Uuid',
        'input': 'ShotData',
        'length': 'int',
        'loop_mode': 'str',
        'slip': 'int'
    }

    attribute_map = {
        'grade': 'grade',
        'input_uuid': 'input_uuid',
        'input': 'input',
        'length': 'length',
        'loop_mode': 'loop_mode',
        'slip': 'slip'
    }

    def __init__(self, grade=None, input_uuid=None, input=None, length=None, loop_mode=None, slip=None):  # noqa: E501
        """InputData - a model defined in Swagger"""  # noqa: E501
        self._grade = None
        self._input_uuid = None
        self._input = None
        self._length = None
        self._loop_mode = None
        self._slip = None
        self.discriminator = None
        if grade is not None:
            self.grade = grade
        if input_uuid is not None:
            self.input_uuid = input_uuid
        if input is not None:
            self.input = input
        if length is not None:
            self.length = length
        if loop_mode is not None:
            self.loop_mode = loop_mode
        if slip is not None:
            self.slip = slip

    @property
    def grade(self):
        """Gets the grade of this InputData.  # noqa: E501

        render the grade of the Input Shot  # noqa: E501

        :return: The grade of this InputData.  # noqa: E501
        :rtype: bool
        """
        return self._grade

    @grade.setter
    def grade(self, grade):
        """Sets the grade of this InputData.

        render the grade of the Input Shot  # noqa: E501

        :param grade: The grade of this InputData.  # noqa: E501
        :type: bool
        """

        self._grade = grade

    @property
    def input_uuid(self):
        """Gets the input_uuid of this InputData.  # noqa: E501


        :return: The input_uuid of this InputData.  # noqa: E501
        :rtype: Uuid
        """
        return self._input_uuid

    @input_uuid.setter
    def input_uuid(self, input_uuid):
        """Sets the input_uuid of this InputData.


        :param input_uuid: The input_uuid of this InputData.  # noqa: E501
        :type: Uuid
        """

        self._input_uuid = input_uuid

    @property
    def input(self):
        """Gets the input of this InputData.  # noqa: E501


        :return: The input of this InputData.  # noqa: E501
        :rtype: ShotData
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this InputData.


        :param input: The input of this InputData.  # noqa: E501
        :type: ShotData
        """

        self._input = input

    @property
    def length(self):
        """Gets the length of this InputData.  # noqa: E501

        Length of the Input Shot in frames  # noqa: E501

        :return: The length of this InputData.  # noqa: E501
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this InputData.

        Length of the Input Shot in frames  # noqa: E501

        :param length: The length of this InputData.  # noqa: E501
        :type: int
        """

        self._length = length

    @property
    def loop_mode(self):
        """Gets the loop_mode of this InputData.  # noqa: E501

        Loop mode of the Input Shot  # noqa: E501

        :return: The loop_mode of this InputData.  # noqa: E501
        :rtype: str
        """
        return self._loop_mode

    @loop_mode.setter
    def loop_mode(self, loop_mode):
        """Sets the loop_mode of this InputData.

        Loop mode of the Input Shot  # noqa: E501

        :param loop_mode: The loop_mode of this InputData.  # noqa: E501
        :type: str
        """

        self._loop_mode = loop_mode

    @property
    def slip(self):
        """Gets the slip of this InputData.  # noqa: E501

        Shot in-point.  # noqa: E501

        :return: The slip of this InputData.  # noqa: E501
        :rtype: int
        """
        return self._slip

    @slip.setter
    def slip(self, slip):
        """Sets the slip of this InputData.

        Shot in-point.  # noqa: E501

        :param slip: The slip of this InputData.  # noqa: E501
        :type: int
        """

        self._slip = slip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InputData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InputData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
