# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KeyFrameData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'li': 'float',
        'lv': 'float',
        'ki': 'float',
        'kv': 'float',
        'ri': 'float',
        'rv': 'float'
    }

    attribute_map = {
        'li': 'li',
        'lv': 'lv',
        'ki': 'ki',
        'kv': 'kv',
        'ri': 'ri',
        'rv': 'rv'
    }

    def __init__(self, li=None, lv=None, ki=None, kv=None, ri=None, rv=None):  # noqa: E501
        """KeyFrameData - a model defined in Swagger"""  # noqa: E501
        self._li = None
        self._lv = None
        self._ki = None
        self._kv = None
        self._ri = None
        self._rv = None
        self.discriminator = None
        if li is not None:
            self.li = li
        if lv is not None:
            self.lv = lv
        self.ki = ki
        self.kv = kv
        if ri is not None:
            self.ri = ri
        if rv is not None:
            self.rv = rv

    @property
    def li(self):
        """Gets the li of this KeyFrameData.  # noqa: E501

        Left tangent line position  # noqa: E501

        :return: The li of this KeyFrameData.  # noqa: E501
        :rtype: float
        """
        return self._li

    @li.setter
    def li(self, li):
        """Sets the li of this KeyFrameData.

        Left tangent line position  # noqa: E501

        :param li: The li of this KeyFrameData.  # noqa: E501
        :type: float
        """

        self._li = li

    @property
    def lv(self):
        """Gets the lv of this KeyFrameData.  # noqa: E501

        Left tangent line value  # noqa: E501

        :return: The lv of this KeyFrameData.  # noqa: E501
        :rtype: float
        """
        return self._lv

    @lv.setter
    def lv(self, lv):
        """Sets the lv of this KeyFrameData.

        Left tangent line value  # noqa: E501

        :param lv: The lv of this KeyFrameData.  # noqa: E501
        :type: float
        """

        self._lv = lv

    @property
    def ki(self):
        """Gets the ki of this KeyFrameData.  # noqa: E501

        Key position  # noqa: E501

        :return: The ki of this KeyFrameData.  # noqa: E501
        :rtype: float
        """
        return self._ki

    @ki.setter
    def ki(self, ki):
        """Sets the ki of this KeyFrameData.

        Key position  # noqa: E501

        :param ki: The ki of this KeyFrameData.  # noqa: E501
        :type: float
        """
        if ki is None:
            raise ValueError("Invalid value for `ki`, must not be `None`")  # noqa: E501

        self._ki = ki

    @property
    def kv(self):
        """Gets the kv of this KeyFrameData.  # noqa: E501

        Key value  # noqa: E501

        :return: The kv of this KeyFrameData.  # noqa: E501
        :rtype: float
        """
        return self._kv

    @kv.setter
    def kv(self, kv):
        """Sets the kv of this KeyFrameData.

        Key value  # noqa: E501

        :param kv: The kv of this KeyFrameData.  # noqa: E501
        :type: float
        """
        if kv is None:
            raise ValueError("Invalid value for `kv`, must not be `None`")  # noqa: E501

        self._kv = kv

    @property
    def ri(self):
        """Gets the ri of this KeyFrameData.  # noqa: E501

        Right tangent line position  # noqa: E501

        :return: The ri of this KeyFrameData.  # noqa: E501
        :rtype: float
        """
        return self._ri

    @ri.setter
    def ri(self, ri):
        """Sets the ri of this KeyFrameData.

        Right tangent line position  # noqa: E501

        :param ri: The ri of this KeyFrameData.  # noqa: E501
        :type: float
        """

        self._ri = ri

    @property
    def rv(self):
        """Gets the rv of this KeyFrameData.  # noqa: E501

        Right tangent line value  # noqa: E501

        :return: The rv of this KeyFrameData.  # noqa: E501
        :rtype: float
        """
        return self._rv

    @rv.setter
    def rv(self, rv):
        """Sets the rv of this KeyFrameData.

        Right tangent line value  # noqa: E501

        :param rv: The rv of this KeyFrameData.  # noqa: E501
        :type: float
        """

        self._rv = rv

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeyFrameData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeyFrameData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
