# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MoveShotData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create_copy': 'bool',
        'construct_uuid': 'Uuid',
        'slot_id': 'int',
        'version_id': 'int',
        'tray_name': 'str',
        'tray_frame': 'int',
        'tray_slip': 'int',
        'tray_position': 'int'
    }

    attribute_map = {
        'create_copy': 'create_copy',
        'construct_uuid': 'construct_uuid',
        'slot_id': 'slot_id',
        'version_id': 'version_id',
        'tray_name': 'tray_name',
        'tray_frame': 'tray_frame',
        'tray_slip': 'tray_slip',
        'tray_position': 'tray_position'
    }

    def __init__(self, create_copy=None, construct_uuid=None, slot_id=None, version_id=None, tray_name=None, tray_frame=None, tray_slip=None, tray_position=None):  # noqa: E501
        """MoveShotData - a model defined in Swagger"""  # noqa: E501
        self._create_copy = None
        self._construct_uuid = None
        self._slot_id = None
        self._version_id = None
        self._tray_name = None
        self._tray_frame = None
        self._tray_slip = None
        self._tray_position = None
        self.discriminator = None
        if create_copy is not None:
            self.create_copy = create_copy
        if construct_uuid is not None:
            self.construct_uuid = construct_uuid
        if slot_id is not None:
            self.slot_id = slot_id
        if version_id is not None:
            self.version_id = version_id
        if tray_name is not None:
            self.tray_name = tray_name
        if tray_frame is not None:
            self.tray_frame = tray_frame
        if tray_slip is not None:
            self.tray_slip = tray_slip
        if tray_position is not None:
            self.tray_position = tray_position

    @property
    def create_copy(self):
        """Gets the create_copy of this MoveShotData.  # noqa: E501

        Create a copy of the Shot  # noqa: E501

        :return: The create_copy of this MoveShotData.  # noqa: E501
        :rtype: bool
        """
        return self._create_copy

    @create_copy.setter
    def create_copy(self, create_copy):
        """Sets the create_copy of this MoveShotData.

        Create a copy of the Shot  # noqa: E501

        :param create_copy: The create_copy of this MoveShotData.  # noqa: E501
        :type: bool
        """

        self._create_copy = create_copy

    @property
    def construct_uuid(self):
        """Gets the construct_uuid of this MoveShotData.  # noqa: E501


        :return: The construct_uuid of this MoveShotData.  # noqa: E501
        :rtype: Uuid
        """
        return self._construct_uuid

    @construct_uuid.setter
    def construct_uuid(self, construct_uuid):
        """Sets the construct_uuid of this MoveShotData.


        :param construct_uuid: The construct_uuid of this MoveShotData.  # noqa: E501
        :type: Uuid
        """

        self._construct_uuid = construct_uuid

    @property
    def slot_id(self):
        """Gets the slot_id of this MoveShotData.  # noqa: E501

        Move the Shot to a Slot with slot_id in the Construct  # noqa: E501

        :return: The slot_id of this MoveShotData.  # noqa: E501
        :rtype: int
        """
        return self._slot_id

    @slot_id.setter
    def slot_id(self, slot_id):
        """Sets the slot_id of this MoveShotData.

        Move the Shot to a Slot with slot_id in the Construct  # noqa: E501

        :param slot_id: The slot_id of this MoveShotData.  # noqa: E501
        :type: int
        """

        self._slot_id = slot_id

    @property
    def version_id(self):
        """Gets the version_id of this MoveShotData.  # noqa: E501

        Move the Shot to the version index in the Slot  # noqa: E501

        :return: The version_id of this MoveShotData.  # noqa: E501
        :rtype: int
        """
        return self._version_id

    @version_id.setter
    def version_id(self, version_id):
        """Sets the version_id of this MoveShotData.

        Move the Shot to the version index in the Slot  # noqa: E501

        :param version_id: The version_id of this MoveShotData.  # noqa: E501
        :type: int
        """

        self._version_id = version_id

    @property
    def tray_name(self):
        """Gets the tray_name of this MoveShotData.  # noqa: E501

        Move the Shot to the Tray with name  # noqa: E501

        :return: The tray_name of this MoveShotData.  # noqa: E501
        :rtype: str
        """
        return self._tray_name

    @tray_name.setter
    def tray_name(self, tray_name):
        """Sets the tray_name of this MoveShotData.

        Move the Shot to the Tray with name  # noqa: E501

        :param tray_name: The tray_name of this MoveShotData.  # noqa: E501
        :type: str
        """

        self._tray_name = tray_name

    @property
    def tray_frame(self):
        """Gets the tray_frame of this MoveShotData.  # noqa: E501

        The frame to use for the proxy image  # noqa: E501

        :return: The tray_frame of this MoveShotData.  # noqa: E501
        :rtype: int
        """
        return self._tray_frame

    @tray_frame.setter
    def tray_frame(self, tray_frame):
        """Sets the tray_frame of this MoveShotData.

        The frame to use for the proxy image  # noqa: E501

        :param tray_frame: The tray_frame of this MoveShotData.  # noqa: E501
        :type: int
        """

        self._tray_frame = tray_frame

    @property
    def tray_slip(self):
        """Gets the tray_slip of this MoveShotData.  # noqa: E501

        The frame slip to use when playing in split view  # noqa: E501

        :return: The tray_slip of this MoveShotData.  # noqa: E501
        :rtype: int
        """
        return self._tray_slip

    @tray_slip.setter
    def tray_slip(self, tray_slip):
        """Sets the tray_slip of this MoveShotData.

        The frame slip to use when playing in split view  # noqa: E501

        :param tray_slip: The tray_slip of this MoveShotData.  # noqa: E501
        :type: int
        """

        self._tray_slip = tray_slip

    @property
    def tray_position(self):
        """Gets the tray_position of this MoveShotData.  # noqa: E501

        Position index in the tray  # noqa: E501

        :return: The tray_position of this MoveShotData.  # noqa: E501
        :rtype: int
        """
        return self._tray_position

    @tray_position.setter
    def tray_position(self, tray_position):
        """Sets the tray_position of this MoveShotData.

        Position index in the tray  # noqa: E501

        :param tray_position: The tray_position of this MoveShotData.  # noqa: E501
        :type: int
        """

        self._tray_position = tray_position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MoveShotData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MoveShotData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
