# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MoveConstructData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create_copy': 'bool',
        'construct_uuid': 'Uuid',
        'group_uuid': 'Uuid',
        'position_index': 'int'
    }

    attribute_map = {
        'create_copy': 'create_copy',
        'construct_uuid': 'construct_uuid',
        'group_uuid': 'group_uuid',
        'position_index': 'position_index'
    }

    def __init__(self, create_copy=None, construct_uuid=None, group_uuid=None, position_index=None):  # noqa: E501
        """MoveConstructData - a model defined in Swagger"""  # noqa: E501
        self._create_copy = None
        self._construct_uuid = None
        self._group_uuid = None
        self._position_index = None
        self.discriminator = None
        if create_copy is not None:
            self.create_copy = create_copy
        if construct_uuid is not None:
            self.construct_uuid = construct_uuid
        if group_uuid is not None:
            self.group_uuid = group_uuid
        if position_index is not None:
            self.position_index = position_index

    @property
    def create_copy(self):
        """Gets the create_copy of this MoveConstructData.  # noqa: E501

        Create a copy of the Construct or move it  # noqa: E501

        :return: The create_copy of this MoveConstructData.  # noqa: E501
        :rtype: bool
        """
        return self._create_copy

    @create_copy.setter
    def create_copy(self, create_copy):
        """Sets the create_copy of this MoveConstructData.

        Create a copy of the Construct or move it  # noqa: E501

        :param create_copy: The create_copy of this MoveConstructData.  # noqa: E501
        :type: bool
        """

        self._create_copy = create_copy

    @property
    def construct_uuid(self):
        """Gets the construct_uuid of this MoveConstructData.  # noqa: E501


        :return: The construct_uuid of this MoveConstructData.  # noqa: E501
        :rtype: Uuid
        """
        return self._construct_uuid

    @construct_uuid.setter
    def construct_uuid(self, construct_uuid):
        """Sets the construct_uuid of this MoveConstructData.


        :param construct_uuid: The construct_uuid of this MoveConstructData.  # noqa: E501
        :type: Uuid
        """

        self._construct_uuid = construct_uuid

    @property
    def group_uuid(self):
        """Gets the group_uuid of this MoveConstructData.  # noqa: E501


        :return: The group_uuid of this MoveConstructData.  # noqa: E501
        :rtype: Uuid
        """
        return self._group_uuid

    @group_uuid.setter
    def group_uuid(self, group_uuid):
        """Sets the group_uuid of this MoveConstructData.


        :param group_uuid: The group_uuid of this MoveConstructData.  # noqa: E501
        :type: Uuid
        """

        self._group_uuid = group_uuid

    @property
    def position_index(self):
        """Gets the position_index of this MoveConstructData.  # noqa: E501

        Position index in the Group to move or copy the Construct to  # noqa: E501

        :return: The position_index of this MoveConstructData.  # noqa: E501
        :rtype: int
        """
        return self._position_index

    @position_index.setter
    def position_index(self, position_index):
        """Sets the position_index of this MoveConstructData.

        Position index in the Group to move or copy the Construct to  # noqa: E501

        :param position_index: The position_index of this MoveConstructData.  # noqa: E501
        :type: int
        """

        self._position_index = position_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MoveConstructData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MoveConstructData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
