# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NoteData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'author': 'str',
        'frame': 'int',
        'id': 'int',
        'note': 'str'
    }

    attribute_map = {
        'status': 'status',
        'author': 'author',
        'frame': 'frame',
        'id': 'id',
        'note': 'note'
    }

    def __init__(self, status=None, author=None, frame=None, id=None, note=None):  # noqa: E501
        """NoteData - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._author = None
        self._frame = None
        self._id = None
        self._note = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if author is not None:
            self.author = author
        if frame is not None:
            self.frame = frame
        if id is not None:
            self.id = id
        if note is not None:
            self.note = note

    @property
    def status(self):
        """Gets the status of this NoteData.  # noqa: E501

        Color of the note  # noqa: E501

        :return: The status of this NoteData.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this NoteData.

        Color of the note  # noqa: E501

        :param status: The status of this NoteData.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def author(self):
        """Gets the author of this NoteData.  # noqa: E501

        Author of the note  # noqa: E501

        :return: The author of this NoteData.  # noqa: E501
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this NoteData.

        Author of the note  # noqa: E501

        :param author: The author of this NoteData.  # noqa: E501
        :type: str
        """

        self._author = author

    @property
    def frame(self):
        """Gets the frame of this NoteData.  # noqa: E501

        Frame number in the Shot of the note  # noqa: E501

        :return: The frame of this NoteData.  # noqa: E501
        :rtype: int
        """
        return self._frame

    @frame.setter
    def frame(self, frame):
        """Sets the frame of this NoteData.

        Frame number in the Shot of the note  # noqa: E501

        :param frame: The frame of this NoteData.  # noqa: E501
        :type: int
        """

        self._frame = frame

    @property
    def id(self):
        """Gets the id of this NoteData.  # noqa: E501

        Unique identifier of the note  # noqa: E501

        :return: The id of this NoteData.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NoteData.

        Unique identifier of the note  # noqa: E501

        :param id: The id of this NoteData.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def note(self):
        """Gets the note of this NoteData.  # noqa: E501

        Content of the note  # noqa: E501

        :return: The note of this NoteData.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this NoteData.

        Content of the note  # noqa: E501

        :param note: The note of this NoteData.  # noqa: E501
        :type: str
        """

        self._note = note

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NoteData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NoteData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
