# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'project_paths': 'ProjectDataProjectPaths',
        'def_image_format': 'ProjectDataDefImageFormat',
        'def_output_template': 'ProjectDataDefOutputTemplate',
        'def_output_format': 'ProjectDataDefOutputFormat',
        'color_management': 'ProjectDataColorManagement',
        'hdr_metadata': 'ProjectDataHdrMetadata'
    }

    attribute_map = {
        'name': 'name',
        'project_paths': 'project_paths',
        'def_image_format': 'def_image_format',
        'def_output_template': 'def_output_template',
        'def_output_format': 'def_output_format',
        'color_management': 'color_management',
        'hdr_metadata': 'hdr_metadata'
    }

    def __init__(self, name=None, project_paths=None, def_image_format=None, def_output_template=None, def_output_format=None, color_management=None, hdr_metadata=None):  # noqa: E501
        """ProjectData - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._project_paths = None
        self._def_image_format = None
        self._def_output_template = None
        self._def_output_format = None
        self._color_management = None
        self._hdr_metadata = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if project_paths is not None:
            self.project_paths = project_paths
        if def_image_format is not None:
            self.def_image_format = def_image_format
        if def_output_template is not None:
            self.def_output_template = def_output_template
        if def_output_format is not None:
            self.def_output_format = def_output_format
        if color_management is not None:
            self.color_management = color_management
        if hdr_metadata is not None:
            self.hdr_metadata = hdr_metadata

    @property
    def name(self):
        """Gets the name of this ProjectData.  # noqa: E501

        Name of the Project  # noqa: E501

        :return: The name of this ProjectData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectData.

        Name of the Project  # noqa: E501

        :param name: The name of this ProjectData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def project_paths(self):
        """Gets the project_paths of this ProjectData.  # noqa: E501


        :return: The project_paths of this ProjectData.  # noqa: E501
        :rtype: ProjectDataProjectPaths
        """
        return self._project_paths

    @project_paths.setter
    def project_paths(self, project_paths):
        """Sets the project_paths of this ProjectData.


        :param project_paths: The project_paths of this ProjectData.  # noqa: E501
        :type: ProjectDataProjectPaths
        """

        self._project_paths = project_paths

    @property
    def def_image_format(self):
        """Gets the def_image_format of this ProjectData.  # noqa: E501


        :return: The def_image_format of this ProjectData.  # noqa: E501
        :rtype: ProjectDataDefImageFormat
        """
        return self._def_image_format

    @def_image_format.setter
    def def_image_format(self, def_image_format):
        """Sets the def_image_format of this ProjectData.


        :param def_image_format: The def_image_format of this ProjectData.  # noqa: E501
        :type: ProjectDataDefImageFormat
        """

        self._def_image_format = def_image_format

    @property
    def def_output_template(self):
        """Gets the def_output_template of this ProjectData.  # noqa: E501


        :return: The def_output_template of this ProjectData.  # noqa: E501
        :rtype: ProjectDataDefOutputTemplate
        """
        return self._def_output_template

    @def_output_template.setter
    def def_output_template(self, def_output_template):
        """Sets the def_output_template of this ProjectData.


        :param def_output_template: The def_output_template of this ProjectData.  # noqa: E501
        :type: ProjectDataDefOutputTemplate
        """

        self._def_output_template = def_output_template

    @property
    def def_output_format(self):
        """Gets the def_output_format of this ProjectData.  # noqa: E501


        :return: The def_output_format of this ProjectData.  # noqa: E501
        :rtype: ProjectDataDefOutputFormat
        """
        return self._def_output_format

    @def_output_format.setter
    def def_output_format(self, def_output_format):
        """Sets the def_output_format of this ProjectData.


        :param def_output_format: The def_output_format of this ProjectData.  # noqa: E501
        :type: ProjectDataDefOutputFormat
        """

        self._def_output_format = def_output_format

    @property
    def color_management(self):
        """Gets the color_management of this ProjectData.  # noqa: E501


        :return: The color_management of this ProjectData.  # noqa: E501
        :rtype: ProjectDataColorManagement
        """
        return self._color_management

    @color_management.setter
    def color_management(self, color_management):
        """Sets the color_management of this ProjectData.


        :param color_management: The color_management of this ProjectData.  # noqa: E501
        :type: ProjectDataColorManagement
        """

        self._color_management = color_management

    @property
    def hdr_metadata(self):
        """Gets the hdr_metadata of this ProjectData.  # noqa: E501


        :return: The hdr_metadata of this ProjectData.  # noqa: E501
        :rtype: ProjectDataHdrMetadata
        """
        return self._hdr_metadata

    @hdr_metadata.setter
    def hdr_metadata(self, hdr_metadata):
        """Sets the hdr_metadata of this ProjectData.


        :param hdr_metadata: The hdr_metadata of this ProjectData.  # noqa: E501
        :type: ProjectDataHdrMetadata
        """

        self._hdr_metadata = hdr_metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
