# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectDataProjectPaths(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'media_path': 'str',
        'render_path': 'str',
        'cache_path': 'str'
    }

    attribute_map = {
        'media_path': 'media_path',
        'render_path': 'render_path',
        'cache_path': 'cache_path'
    }

    def __init__(self, media_path=None, render_path=None, cache_path=None):  # noqa: E501
        """ProjectDataProjectPaths - a model defined in Swagger"""  # noqa: E501
        self._media_path = None
        self._render_path = None
        self._cache_path = None
        self.discriminator = None
        if media_path is not None:
            self.media_path = media_path
        if render_path is not None:
            self.render_path = render_path
        if cache_path is not None:
            self.cache_path = cache_path

    @property
    def media_path(self):
        """Gets the media_path of this ProjectDataProjectPaths.  # noqa: E501

        Default media path for the Project  # noqa: E501

        :return: The media_path of this ProjectDataProjectPaths.  # noqa: E501
        :rtype: str
        """
        return self._media_path

    @media_path.setter
    def media_path(self, media_path):
        """Sets the media_path of this ProjectDataProjectPaths.

        Default media path for the Project  # noqa: E501

        :param media_path: The media_path of this ProjectDataProjectPaths.  # noqa: E501
        :type: str
        """

        self._media_path = media_path

    @property
    def render_path(self):
        """Gets the render_path of this ProjectDataProjectPaths.  # noqa: E501

        Default render path for the Project  # noqa: E501

        :return: The render_path of this ProjectDataProjectPaths.  # noqa: E501
        :rtype: str
        """
        return self._render_path

    @render_path.setter
    def render_path(self, render_path):
        """Sets the render_path of this ProjectDataProjectPaths.

        Default render path for the Project  # noqa: E501

        :param render_path: The render_path of this ProjectDataProjectPaths.  # noqa: E501
        :type: str
        """

        self._render_path = render_path

    @property
    def cache_path(self):
        """Gets the cache_path of this ProjectDataProjectPaths.  # noqa: E501

        Default cache path for the Project  # noqa: E501

        :return: The cache_path of this ProjectDataProjectPaths.  # noqa: E501
        :rtype: str
        """
        return self._cache_path

    @cache_path.setter
    def cache_path(self, cache_path):
        """Sets the cache_path of this ProjectDataProjectPaths.

        Default cache path for the Project  # noqa: E501

        :param cache_path: The cache_path of this ProjectDataProjectPaths.  # noqa: E501
        :type: str
        """

        self._cache_path = cache_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectDataProjectPaths, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDataProjectPaths):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
