# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectDataHdrMetadataPrimaries(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'red_x': 'float',
        'red_y': 'float',
        'green_x': 'float',
        'green_y': 'float',
        'blue_x': 'float',
        'blue_y': 'float',
        'white_x': 'float',
        'white_y': 'float',
        'lum_min': 'float',
        'lum_max': 'float',
        'max_cll': 'float',
        'max_fall': 'float'
    }

    attribute_map = {
        'red_x': 'red_x',
        'red_y': 'red_y',
        'green_x': 'green_x',
        'green_y': 'green_y',
        'blue_x': 'blue_x',
        'blue_y': 'blue_y',
        'white_x': 'white_x',
        'white_y': 'white_y',
        'lum_min': 'lum_min',
        'lum_max': 'lum_max',
        'max_cll': 'max_cll',
        'max_fall': 'max_fall'
    }

    def __init__(self, red_x=None, red_y=None, green_x=None, green_y=None, blue_x=None, blue_y=None, white_x=None, white_y=None, lum_min=None, lum_max=None, max_cll=None, max_fall=None):  # noqa: E501
        """ProjectDataHdrMetadataPrimaries - a model defined in Swagger"""  # noqa: E501
        self._red_x = None
        self._red_y = None
        self._green_x = None
        self._green_y = None
        self._blue_x = None
        self._blue_y = None
        self._white_x = None
        self._white_y = None
        self._lum_min = None
        self._lum_max = None
        self._max_cll = None
        self._max_fall = None
        self.discriminator = None
        if red_x is not None:
            self.red_x = red_x
        if red_y is not None:
            self.red_y = red_y
        if green_x is not None:
            self.green_x = green_x
        if green_y is not None:
            self.green_y = green_y
        if blue_x is not None:
            self.blue_x = blue_x
        if blue_y is not None:
            self.blue_y = blue_y
        if white_x is not None:
            self.white_x = white_x
        if white_y is not None:
            self.white_y = white_y
        if lum_min is not None:
            self.lum_min = lum_min
        if lum_max is not None:
            self.lum_max = lum_max
        if max_cll is not None:
            self.max_cll = max_cll
        if max_fall is not None:
            self.max_fall = max_fall

    @property
    def red_x(self):
        """Gets the red_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Red primary X value  # noqa: E501

        :return: The red_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._red_x

    @red_x.setter
    def red_x(self, red_x):
        """Sets the red_x of this ProjectDataHdrMetadataPrimaries.

        Red primary X value  # noqa: E501

        :param red_x: The red_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._red_x = red_x

    @property
    def red_y(self):
        """Gets the red_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Red primary Y value  # noqa: E501

        :return: The red_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._red_y

    @red_y.setter
    def red_y(self, red_y):
        """Sets the red_y of this ProjectDataHdrMetadataPrimaries.

        Red primary Y value  # noqa: E501

        :param red_y: The red_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._red_y = red_y

    @property
    def green_x(self):
        """Gets the green_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Green primary X value  # noqa: E501

        :return: The green_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._green_x

    @green_x.setter
    def green_x(self, green_x):
        """Sets the green_x of this ProjectDataHdrMetadataPrimaries.

        Green primary X value  # noqa: E501

        :param green_x: The green_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._green_x = green_x

    @property
    def green_y(self):
        """Gets the green_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Green primary Y value  # noqa: E501

        :return: The green_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._green_y

    @green_y.setter
    def green_y(self, green_y):
        """Sets the green_y of this ProjectDataHdrMetadataPrimaries.

        Green primary Y value  # noqa: E501

        :param green_y: The green_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._green_y = green_y

    @property
    def blue_x(self):
        """Gets the blue_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Blue primary X value  # noqa: E501

        :return: The blue_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._blue_x

    @blue_x.setter
    def blue_x(self, blue_x):
        """Sets the blue_x of this ProjectDataHdrMetadataPrimaries.

        Blue primary X value  # noqa: E501

        :param blue_x: The blue_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._blue_x = blue_x

    @property
    def blue_y(self):
        """Gets the blue_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Blue primary Y value  # noqa: E501

        :return: The blue_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._blue_y

    @blue_y.setter
    def blue_y(self, blue_y):
        """Sets the blue_y of this ProjectDataHdrMetadataPrimaries.

        Blue primary Y value  # noqa: E501

        :param blue_y: The blue_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._blue_y = blue_y

    @property
    def white_x(self):
        """Gets the white_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        White point X value  # noqa: E501

        :return: The white_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._white_x

    @white_x.setter
    def white_x(self, white_x):
        """Sets the white_x of this ProjectDataHdrMetadataPrimaries.

        White point X value  # noqa: E501

        :param white_x: The white_x of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._white_x = white_x

    @property
    def white_y(self):
        """Gets the white_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        White point Y value  # noqa: E501

        :return: The white_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._white_y

    @white_y.setter
    def white_y(self, white_y):
        """Sets the white_y of this ProjectDataHdrMetadataPrimaries.

        White point Y value  # noqa: E501

        :param white_y: The white_y of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._white_y = white_y

    @property
    def lum_min(self):
        """Gets the lum_min of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Minimum luminance  # noqa: E501

        :return: The lum_min of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._lum_min

    @lum_min.setter
    def lum_min(self, lum_min):
        """Sets the lum_min of this ProjectDataHdrMetadataPrimaries.

        Minimum luminance  # noqa: E501

        :param lum_min: The lum_min of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._lum_min = lum_min

    @property
    def lum_max(self):
        """Gets the lum_max of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Maximum luminance  # noqa: E501

        :return: The lum_max of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._lum_max

    @lum_max.setter
    def lum_max(self, lum_max):
        """Sets the lum_max of this ProjectDataHdrMetadataPrimaries.

        Maximum luminance  # noqa: E501

        :param lum_max: The lum_max of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._lum_max = lum_max

    @property
    def max_cll(self):
        """Gets the max_cll of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Maximum content light level  # noqa: E501

        :return: The max_cll of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._max_cll

    @max_cll.setter
    def max_cll(self, max_cll):
        """Sets the max_cll of this ProjectDataHdrMetadataPrimaries.

        Maximum content light level  # noqa: E501

        :param max_cll: The max_cll of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._max_cll = max_cll

    @property
    def max_fall(self):
        """Gets the max_fall of this ProjectDataHdrMetadataPrimaries.  # noqa: E501

        Maximum frame average light level  # noqa: E501

        :return: The max_fall of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :rtype: float
        """
        return self._max_fall

    @max_fall.setter
    def max_fall(self, max_fall):
        """Sets the max_fall of this ProjectDataHdrMetadataPrimaries.

        Maximum frame average light level  # noqa: E501

        :param max_fall: The max_fall of this ProjectDataHdrMetadataPrimaries.  # noqa: E501
        :type: float
        """

        self._max_fall = max_fall

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectDataHdrMetadataPrimaries, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDataHdrMetadataPrimaries):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
