# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectDataHdrMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mode': 'str',
        'eotf': 'str',
        'primaries': 'ProjectDataHdrMetadataPrimaries'
    }

    attribute_map = {
        'mode': 'mode',
        'eotf': 'eotf',
        'primaries': 'primaries'
    }

    def __init__(self, mode=None, eotf=None, primaries=None):  # noqa: E501
        """ProjectDataHdrMetadata - a model defined in Swagger"""  # noqa: E501
        self._mode = None
        self._eotf = None
        self._primaries = None
        self.discriminator = None
        if mode is not None:
            self.mode = mode
        if eotf is not None:
            self.eotf = eotf
        if primaries is not None:
            self.primaries = primaries

    @property
    def mode(self):
        """Gets the mode of this ProjectDataHdrMetadata.  # noqa: E501

        HDR metadata mode  # noqa: E501

        :return: The mode of this ProjectDataHdrMetadata.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this ProjectDataHdrMetadata.

        HDR metadata mode  # noqa: E501

        :param mode: The mode of this ProjectDataHdrMetadata.  # noqa: E501
        :type: str
        """

        self._mode = mode

    @property
    def eotf(self):
        """Gets the eotf of this ProjectDataHdrMetadata.  # noqa: E501

        EOTF for HDR metadata  # noqa: E501

        :return: The eotf of this ProjectDataHdrMetadata.  # noqa: E501
        :rtype: str
        """
        return self._eotf

    @eotf.setter
    def eotf(self, eotf):
        """Sets the eotf of this ProjectDataHdrMetadata.

        EOTF for HDR metadata  # noqa: E501

        :param eotf: The eotf of this ProjectDataHdrMetadata.  # noqa: E501
        :type: str
        """

        self._eotf = eotf

    @property
    def primaries(self):
        """Gets the primaries of this ProjectDataHdrMetadata.  # noqa: E501


        :return: The primaries of this ProjectDataHdrMetadata.  # noqa: E501
        :rtype: ProjectDataHdrMetadataPrimaries
        """
        return self._primaries

    @primaries.setter
    def primaries(self, primaries):
        """Sets the primaries of this ProjectDataHdrMetadata.


        :param primaries: The primaries of this ProjectDataHdrMetadata.  # noqa: E501
        :type: ProjectDataHdrMetadataPrimaries
        """

        self._primaries = primaries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectDataHdrMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDataHdrMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
