# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectDataColorManagement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enable': 'bool',
        'acess_version': 'float',
        'acess_log': 'str'
    }

    attribute_map = {
        'enable': 'enable',
        'acess_version': 'acess_version',
        'acess_log': 'acess_log'
    }

    def __init__(self, enable=None, acess_version=None, acess_log=None):  # noqa: E501
        """ProjectDataColorManagement - a model defined in Swagger"""  # noqa: E501
        self._enable = None
        self._acess_version = None
        self._acess_log = None
        self.discriminator = None
        if enable is not None:
            self.enable = enable
        if acess_version is not None:
            self.acess_version = acess_version
        if acess_log is not None:
            self.acess_log = acess_log

    @property
    def enable(self):
        """Gets the enable of this ProjectDataColorManagement.  # noqa: E501

        Enable / disable color management for the Project  # noqa: E501

        :return: The enable of this ProjectDataColorManagement.  # noqa: E501
        :rtype: bool
        """
        return self._enable

    @enable.setter
    def enable(self, enable):
        """Sets the enable of this ProjectDataColorManagement.

        Enable / disable color management for the Project  # noqa: E501

        :param enable: The enable of this ProjectDataColorManagement.  # noqa: E501
        :type: bool
        """

        self._enable = enable

    @property
    def acess_version(self):
        """Gets the acess_version of this ProjectDataColorManagement.  # noqa: E501

        ACES version  # noqa: E501

        :return: The acess_version of this ProjectDataColorManagement.  # noqa: E501
        :rtype: float
        """
        return self._acess_version

    @acess_version.setter
    def acess_version(self, acess_version):
        """Sets the acess_version of this ProjectDataColorManagement.

        ACES version  # noqa: E501

        :param acess_version: The acess_version of this ProjectDataColorManagement.  # noqa: E501
        :type: float
        """

        self._acess_version = acess_version

    @property
    def acess_log(self):
        """Gets the acess_log of this ProjectDataColorManagement.  # noqa: E501

        ACES format  # noqa: E501

        :return: The acess_log of this ProjectDataColorManagement.  # noqa: E501
        :rtype: str
        """
        return self._acess_log

    @acess_log.setter
    def acess_log(self, acess_log):
        """Sets the acess_log of this ProjectDataColorManagement.

        ACES format  # noqa: E501

        :param acess_log: The acess_log of this ProjectDataColorManagement.  # noqa: E501
        :type: str
        """

        self._acess_log = acess_log

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectDataColorManagement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDataColorManagement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
