# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectDataDefImageFormat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resolution': 'ProjectDataDefImageFormatResolution',
        'aspect': 'float',
        'framerate': 'float'
    }

    attribute_map = {
        'resolution': 'resolution',
        'aspect': 'aspect',
        'framerate': 'framerate'
    }

    def __init__(self, resolution=None, aspect=None, framerate=None):  # noqa: E501
        """ProjectDataDefImageFormat - a model defined in Swagger"""  # noqa: E501
        self._resolution = None
        self._aspect = None
        self._framerate = None
        self.discriminator = None
        if resolution is not None:
            self.resolution = resolution
        if aspect is not None:
            self.aspect = aspect
        if framerate is not None:
            self.framerate = framerate

    @property
    def resolution(self):
        """Gets the resolution of this ProjectDataDefImageFormat.  # noqa: E501


        :return: The resolution of this ProjectDataDefImageFormat.  # noqa: E501
        :rtype: ProjectDataDefImageFormatResolution
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution):
        """Sets the resolution of this ProjectDataDefImageFormat.


        :param resolution: The resolution of this ProjectDataDefImageFormat.  # noqa: E501
        :type: ProjectDataDefImageFormatResolution
        """

        self._resolution = resolution

    @property
    def aspect(self):
        """Gets the aspect of this ProjectDataDefImageFormat.  # noqa: E501

        Pixel aspect ratio  # noqa: E501

        :return: The aspect of this ProjectDataDefImageFormat.  # noqa: E501
        :rtype: float
        """
        return self._aspect

    @aspect.setter
    def aspect(self, aspect):
        """Sets the aspect of this ProjectDataDefImageFormat.

        Pixel aspect ratio  # noqa: E501

        :param aspect: The aspect of this ProjectDataDefImageFormat.  # noqa: E501
        :type: float
        """

        self._aspect = aspect

    @property
    def framerate(self):
        """Gets the framerate of this ProjectDataDefImageFormat.  # noqa: E501

        Frames per second  # noqa: E501

        :return: The framerate of this ProjectDataDefImageFormat.  # noqa: E501
        :rtype: float
        """
        return self._framerate

    @framerate.setter
    def framerate(self, framerate):
        """Sets the framerate of this ProjectDataDefImageFormat.

        Frames per second  # noqa: E501

        :param framerate: The framerate of this ProjectDataDefImageFormat.  # noqa: E501
        :type: float
        """

        self._framerate = framerate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectDataDefImageFormat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDataDefImageFormat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
