# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectListProjects(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'modified': 'str'
    }

    attribute_map = {
        'name': 'name',
        'modified': 'modified'
    }

    def __init__(self, name=None, modified=None):  # noqa: E501
        """ProjectListProjects - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._modified = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if modified is not None:
            self.modified = modified

    @property
    def name(self):
        """Gets the name of this ProjectListProjects.  # noqa: E501

        Project name  # noqa: E501

        :return: The name of this ProjectListProjects.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectListProjects.

        Project name  # noqa: E501

        :param name: The name of this ProjectListProjects.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def modified(self):
        """Gets the modified of this ProjectListProjects.  # noqa: E501

        Last modified date  # noqa: E501

        :return: The modified of this ProjectListProjects.  # noqa: E501
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this ProjectListProjects.

        Last modified date  # noqa: E501

        :param modified: The modified of this ProjectListProjects.  # noqa: E501
        :type: str
        """

        self._modified = modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectListProjects, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectListProjects):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
