# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectDataDefOutputFormat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'colorspace': 'Colorspace',
        'eotf': 'Eotf',
        'bit_depth': 'int',
        'bit_type': 'str',
        'components': 'str',
        'filetype': 'str'
    }

    attribute_map = {
        'colorspace': 'colorspace',
        'eotf': 'eotf',
        'bit_depth': 'bit_depth',
        'bit_type': 'bit_type',
        'components': 'components',
        'filetype': 'filetype'
    }

    def __init__(self, colorspace=None, eotf=None, bit_depth=None, bit_type=None, components=None, filetype=None):  # noqa: E501
        """ProjectDataDefOutputFormat - a model defined in Swagger"""  # noqa: E501
        self._colorspace = None
        self._eotf = None
        self._bit_depth = None
        self._bit_type = None
        self._components = None
        self._filetype = None
        self.discriminator = None
        if colorspace is not None:
            self.colorspace = colorspace
        if eotf is not None:
            self.eotf = eotf
        if bit_depth is not None:
            self.bit_depth = bit_depth
        if bit_type is not None:
            self.bit_type = bit_type
        if components is not None:
            self.components = components
        if filetype is not None:
            self.filetype = filetype

    @property
    def colorspace(self):
        """Gets the colorspace of this ProjectDataDefOutputFormat.  # noqa: E501


        :return: The colorspace of this ProjectDataDefOutputFormat.  # noqa: E501
        :rtype: Colorspace
        """
        return self._colorspace

    @colorspace.setter
    def colorspace(self, colorspace):
        """Sets the colorspace of this ProjectDataDefOutputFormat.


        :param colorspace: The colorspace of this ProjectDataDefOutputFormat.  # noqa: E501
        :type: Colorspace
        """

        self._colorspace = colorspace

    @property
    def eotf(self):
        """Gets the eotf of this ProjectDataDefOutputFormat.  # noqa: E501


        :return: The eotf of this ProjectDataDefOutputFormat.  # noqa: E501
        :rtype: Eotf
        """
        return self._eotf

    @eotf.setter
    def eotf(self, eotf):
        """Sets the eotf of this ProjectDataDefOutputFormat.


        :param eotf: The eotf of this ProjectDataDefOutputFormat.  # noqa: E501
        :type: Eotf
        """

        self._eotf = eotf

    @property
    def bit_depth(self):
        """Gets the bit_depth of this ProjectDataDefOutputFormat.  # noqa: E501

        Default bit depth of a timeline / Construct  # noqa: E501

        :return: The bit_depth of this ProjectDataDefOutputFormat.  # noqa: E501
        :rtype: int
        """
        return self._bit_depth

    @bit_depth.setter
    def bit_depth(self, bit_depth):
        """Sets the bit_depth of this ProjectDataDefOutputFormat.

        Default bit depth of a timeline / Construct  # noqa: E501

        :param bit_depth: The bit_depth of this ProjectDataDefOutputFormat.  # noqa: E501
        :type: int
        """

        self._bit_depth = bit_depth

    @property
    def bit_type(self):
        """Gets the bit_type of this ProjectDataDefOutputFormat.  # noqa: E501

        Default format of a timeline / Construct  # noqa: E501

        :return: The bit_type of this ProjectDataDefOutputFormat.  # noqa: E501
        :rtype: str
        """
        return self._bit_type

    @bit_type.setter
    def bit_type(self, bit_type):
        """Sets the bit_type of this ProjectDataDefOutputFormat.

        Default format of a timeline / Construct  # noqa: E501

        :param bit_type: The bit_type of this ProjectDataDefOutputFormat.  # noqa: E501
        :type: str
        """

        self._bit_type = bit_type

    @property
    def components(self):
        """Gets the components of this ProjectDataDefOutputFormat.  # noqa: E501

        Default channel layout of a timeline / Construct  # noqa: E501

        :return: The components of this ProjectDataDefOutputFormat.  # noqa: E501
        :rtype: str
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this ProjectDataDefOutputFormat.

        Default channel layout of a timeline / Construct  # noqa: E501

        :param components: The components of this ProjectDataDefOutputFormat.  # noqa: E501
        :type: str
        """

        self._components = components

    @property
    def filetype(self):
        """Gets the filetype of this ProjectDataDefOutputFormat.  # noqa: E501

        Default output file format of a timeline / Construct  # noqa: E501

        :return: The filetype of this ProjectDataDefOutputFormat.  # noqa: E501
        :rtype: str
        """
        return self._filetype

    @filetype.setter
    def filetype(self, filetype):
        """Sets the filetype of this ProjectDataDefOutputFormat.

        Default output file format of a timeline / Construct  # noqa: E501

        :param filetype: The filetype of this ProjectDataDefOutputFormat.  # noqa: E501
        :type: str
        """

        self._filetype = filetype

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectDataDefOutputFormat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDataDefOutputFormat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
