# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SelectedShotsDataSelection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'slot_idx': 'int',
        'version_idx': 'int',
        'uuid': 'Uuid',
        'root_uuid': 'Uuid',
        'output_idx': 'int',
        'output_uuid': 'Uuid',
        'shot': 'ShotData'
    }

    attribute_map = {
        'slot_idx': 'slot_idx',
        'version_idx': 'version_idx',
        'uuid': 'uuid',
        'root_uuid': 'root_uuid',
        'output_idx': 'output_idx',
        'output_uuid': 'output_uuid',
        'shot': 'shot'
    }

    def __init__(self, slot_idx=None, version_idx=None, uuid=None, root_uuid=None, output_idx=None, output_uuid=None, shot=None):  # noqa: E501
        """SelectedShotsDataSelection - a model defined in Swagger"""  # noqa: E501
        self._slot_idx = None
        self._version_idx = None
        self._uuid = None
        self._root_uuid = None
        self._output_idx = None
        self._output_uuid = None
        self._shot = None
        self.discriminator = None
        if slot_idx is not None:
            self.slot_idx = slot_idx
        if version_idx is not None:
            self.version_idx = version_idx
        if uuid is not None:
            self.uuid = uuid
        if root_uuid is not None:
            self.root_uuid = root_uuid
        if output_idx is not None:
            self.output_idx = output_idx
        if output_uuid is not None:
            self.output_uuid = output_uuid
        if shot is not None:
            self.shot = shot

    @property
    def slot_idx(self):
        """Gets the slot_idx of this SelectedShotsDataSelection.  # noqa: E501

        Slot index in the construct  # noqa: E501

        :return: The slot_idx of this SelectedShotsDataSelection.  # noqa: E501
        :rtype: int
        """
        return self._slot_idx

    @slot_idx.setter
    def slot_idx(self, slot_idx):
        """Sets the slot_idx of this SelectedShotsDataSelection.

        Slot index in the construct  # noqa: E501

        :param slot_idx: The slot_idx of this SelectedShotsDataSelection.  # noqa: E501
        :type: int
        """

        self._slot_idx = slot_idx

    @property
    def version_idx(self):
        """Gets the version_idx of this SelectedShotsDataSelection.  # noqa: E501

        Version index in the slot  # noqa: E501

        :return: The version_idx of this SelectedShotsDataSelection.  # noqa: E501
        :rtype: int
        """
        return self._version_idx

    @version_idx.setter
    def version_idx(self, version_idx):
        """Sets the version_idx of this SelectedShotsDataSelection.

        Version index in the slot  # noqa: E501

        :param version_idx: The version_idx of this SelectedShotsDataSelection.  # noqa: E501
        :type: int
        """

        self._version_idx = version_idx

    @property
    def uuid(self):
        """Gets the uuid of this SelectedShotsDataSelection.  # noqa: E501


        :return: The uuid of this SelectedShotsDataSelection.  # noqa: E501
        :rtype: Uuid
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this SelectedShotsDataSelection.


        :param uuid: The uuid of this SelectedShotsDataSelection.  # noqa: E501
        :type: Uuid
        """

        self._uuid = uuid

    @property
    def root_uuid(self):
        """Gets the root_uuid of this SelectedShotsDataSelection.  # noqa: E501


        :return: The root_uuid of this SelectedShotsDataSelection.  # noqa: E501
        :rtype: Uuid
        """
        return self._root_uuid

    @root_uuid.setter
    def root_uuid(self, root_uuid):
        """Sets the root_uuid of this SelectedShotsDataSelection.


        :param root_uuid: The root_uuid of this SelectedShotsDataSelection.  # noqa: E501
        :type: Uuid
        """

        self._root_uuid = root_uuid

    @property
    def output_idx(self):
        """Gets the output_idx of this SelectedShotsDataSelection.  # noqa: E501

        Output index of the render node  # noqa: E501

        :return: The output_idx of this SelectedShotsDataSelection.  # noqa: E501
        :rtype: int
        """
        return self._output_idx

    @output_idx.setter
    def output_idx(self, output_idx):
        """Sets the output_idx of this SelectedShotsDataSelection.

        Output index of the render node  # noqa: E501

        :param output_idx: The output_idx of this SelectedShotsDataSelection.  # noqa: E501
        :type: int
        """

        self._output_idx = output_idx

    @property
    def output_uuid(self):
        """Gets the output_uuid of this SelectedShotsDataSelection.  # noqa: E501


        :return: The output_uuid of this SelectedShotsDataSelection.  # noqa: E501
        :rtype: Uuid
        """
        return self._output_uuid

    @output_uuid.setter
    def output_uuid(self, output_uuid):
        """Sets the output_uuid of this SelectedShotsDataSelection.


        :param output_uuid: The output_uuid of this SelectedShotsDataSelection.  # noqa: E501
        :type: Uuid
        """

        self._output_uuid = output_uuid

    @property
    def shot(self):
        """Gets the shot of this SelectedShotsDataSelection.  # noqa: E501


        :return: The shot of this SelectedShotsDataSelection.  # noqa: E501
        :rtype: ShotData
        """
        return self._shot

    @shot.setter
    def shot(self, shot):
        """Sets the shot of this SelectedShotsDataSelection.


        :param shot: The shot of this SelectedShotsDataSelection.  # noqa: E501
        :type: ShotData
        """

        self._shot = shot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SelectedShotsDataSelection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SelectedShotsDataSelection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
