# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SelectedShotsData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group_uuid': 'Uuid',
        'desk_uuid': 'Uuid',
        'selection': 'list[SelectedShotsDataSelection]'
    }

    attribute_map = {
        'group_uuid': 'group_uuid',
        'desk_uuid': 'desk_uuid',
        'selection': 'selection'
    }

    def __init__(self, group_uuid=None, desk_uuid=None, selection=None):  # noqa: E501
        """SelectedShotsData - a model defined in Swagger"""  # noqa: E501
        self._group_uuid = None
        self._desk_uuid = None
        self._selection = None
        self.discriminator = None
        if group_uuid is not None:
            self.group_uuid = group_uuid
        if desk_uuid is not None:
            self.desk_uuid = desk_uuid
        if selection is not None:
            self.selection = selection

    @property
    def group_uuid(self):
        """Gets the group_uuid of this SelectedShotsData.  # noqa: E501


        :return: The group_uuid of this SelectedShotsData.  # noqa: E501
        :rtype: Uuid
        """
        return self._group_uuid

    @group_uuid.setter
    def group_uuid(self, group_uuid):
        """Sets the group_uuid of this SelectedShotsData.


        :param group_uuid: The group_uuid of this SelectedShotsData.  # noqa: E501
        :type: Uuid
        """

        self._group_uuid = group_uuid

    @property
    def desk_uuid(self):
        """Gets the desk_uuid of this SelectedShotsData.  # noqa: E501


        :return: The desk_uuid of this SelectedShotsData.  # noqa: E501
        :rtype: Uuid
        """
        return self._desk_uuid

    @desk_uuid.setter
    def desk_uuid(self, desk_uuid):
        """Sets the desk_uuid of this SelectedShotsData.


        :param desk_uuid: The desk_uuid of this SelectedShotsData.  # noqa: E501
        :type: Uuid
        """

        self._desk_uuid = desk_uuid

    @property
    def selection(self):
        """Gets the selection of this SelectedShotsData.  # noqa: E501


        :return: The selection of this SelectedShotsData.  # noqa: E501
        :rtype: list[SelectedShotsDataSelection]
        """
        return self._selection

    @selection.setter
    def selection(self, selection):
        """Sets the selection of this SelectedShotsData.


        :param selection: The selection of this SelectedShotsData.  # noqa: E501
        :type: list[SelectedShotsDataSelection]
        """

        self._selection = selection

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SelectedShotsData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SelectedShotsData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
