# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShotDataAudio(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timecode': 'Timecode',
        'slip': 'float',
        'roll': 'float',
        'items': 'list[ShotDataAudioItems]'
    }

    attribute_map = {
        'timecode': 'timecode',
        'slip': 'slip',
        'roll': 'roll',
        'items': 'items'
    }

    def __init__(self, timecode=None, slip=None, roll=None, items=None):  # noqa: E501
        """ShotDataAudio - a model defined in Swagger"""  # noqa: E501
        self._timecode = None
        self._slip = None
        self._roll = None
        self._items = None
        self.discriminator = None
        if timecode is not None:
            self.timecode = timecode
        if slip is not None:
            self.slip = slip
        if roll is not None:
            self.roll = roll
        if items is not None:
            self.items = items

    @property
    def timecode(self):
        """Gets the timecode of this ShotDataAudio.  # noqa: E501


        :return: The timecode of this ShotDataAudio.  # noqa: E501
        :rtype: Timecode
        """
        return self._timecode

    @timecode.setter
    def timecode(self, timecode):
        """Sets the timecode of this ShotDataAudio.


        :param timecode: The timecode of this ShotDataAudio.  # noqa: E501
        :type: Timecode
        """

        self._timecode = timecode

    @property
    def slip(self):
        """Gets the slip of this ShotDataAudio.  # noqa: E501

        Slip in milliseconds of all audio items to the video  # noqa: E501

        :return: The slip of this ShotDataAudio.  # noqa: E501
        :rtype: float
        """
        return self._slip

    @slip.setter
    def slip(self, slip):
        """Sets the slip of this ShotDataAudio.

        Slip in milliseconds of all audio items to the video  # noqa: E501

        :param slip: The slip of this ShotDataAudio.  # noqa: E501
        :type: float
        """

        self._slip = slip

    @property
    def roll(self):
        """Gets the roll of this ShotDataAudio.  # noqa: E501

        Roll identifier  # noqa: E501

        :return: The roll of this ShotDataAudio.  # noqa: E501
        :rtype: float
        """
        return self._roll

    @roll.setter
    def roll(self, roll):
        """Sets the roll of this ShotDataAudio.

        Roll identifier  # noqa: E501

        :param roll: The roll of this ShotDataAudio.  # noqa: E501
        :type: float
        """

        self._roll = roll

    @property
    def items(self):
        """Gets the items of this ShotDataAudio.  # noqa: E501

        List of audio items  # noqa: E501

        :return: The items of this ShotDataAudio.  # noqa: E501
        :rtype: list[ShotDataAudioItems]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this ShotDataAudio.

        List of audio items  # noqa: E501

        :param items: The items of this ShotDataAudio.  # noqa: E501
        :type: list[ShotDataAudioItems]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShotDataAudio, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShotDataAudio):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
