# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShotDataOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'outputpath': 'str',
        'filespec': 'str',
        'format': 'int',
        'components': 'int',
        'extention': 'str'
    }

    attribute_map = {
        'outputpath': 'outputpath',
        'filespec': 'filespec',
        'format': 'format',
        'components': 'components',
        'extention': 'extention'
    }

    def __init__(self, outputpath=None, filespec=None, format=None, components=None, extention=None):  # noqa: E501
        """ShotDataOutput - a model defined in Swagger"""  # noqa: E501
        self._outputpath = None
        self._filespec = None
        self._format = None
        self._components = None
        self._extention = None
        self.discriminator = None
        if outputpath is not None:
            self.outputpath = outputpath
        if filespec is not None:
            self.filespec = filespec
        if format is not None:
            self.format = format
        if components is not None:
            self.components = components
        if extention is not None:
            self.extention = extention

    @property
    def outputpath(self):
        """Gets the outputpath of this ShotDataOutput.  # noqa: E501

        Output folder for the render  # noqa: E501

        :return: The outputpath of this ShotDataOutput.  # noqa: E501
        :rtype: str
        """
        return self._outputpath

    @outputpath.setter
    def outputpath(self, outputpath):
        """Sets the outputpath of this ShotDataOutput.

        Output folder for the render  # noqa: E501

        :param outputpath: The outputpath of this ShotDataOutput.  # noqa: E501
        :type: str
        """

        self._outputpath = outputpath

    @property
    def filespec(self):
        """Gets the filespec of this ShotDataOutput.  # noqa: E501

        File specification / mask for the render  # noqa: E501

        :return: The filespec of this ShotDataOutput.  # noqa: E501
        :rtype: str
        """
        return self._filespec

    @filespec.setter
    def filespec(self, filespec):
        """Sets the filespec of this ShotDataOutput.

        File specification / mask for the render  # noqa: E501

        :param filespec: The filespec of this ShotDataOutput.  # noqa: E501
        :type: str
        """

        self._filespec = filespec

    @property
    def format(self):
        """Gets the format of this ShotDataOutput.  # noqa: E501

        Format mask  # noqa: E501

        :return: The format of this ShotDataOutput.  # noqa: E501
        :rtype: int
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this ShotDataOutput.

        Format mask  # noqa: E501

        :param format: The format of this ShotDataOutput.  # noqa: E501
        :type: int
        """

        self._format = format

    @property
    def components(self):
        """Gets the components of this ShotDataOutput.  # noqa: E501

        Channel count (RGB / RGBA)  # noqa: E501

        :return: The components of this ShotDataOutput.  # noqa: E501
        :rtype: int
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this ShotDataOutput.

        Channel count (RGB / RGBA)  # noqa: E501

        :param components: The components of this ShotDataOutput.  # noqa: E501
        :type: int
        """

        self._components = components

    @property
    def extention(self):
        """Gets the extention of this ShotDataOutput.  # noqa: E501

        File extension  # noqa: E501

        :return: The extention of this ShotDataOutput.  # noqa: E501
        :rtype: str
        """
        return self._extention

    @extention.setter
    def extention(self, extention):
        """Sets the extention of this ShotDataOutput.

        File extension  # noqa: E501

        :param extention: The extention of this ShotDataOutput.  # noqa: E501
        :type: str
        """

        self._extention = extention

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShotDataOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShotDataOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
