# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShotDataOrientation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'flip': 'bool',
        'flop': 'bool'
    }

    attribute_map = {
        'flip': 'flip',
        'flop': 'flop'
    }

    def __init__(self, flip=None, flop=None):  # noqa: E501
        """ShotDataOrientation - a model defined in Swagger"""  # noqa: E501
        self._flip = None
        self._flop = None
        self.discriminator = None
        if flip is not None:
            self.flip = flip
        if flop is not None:
            self.flop = flop

    @property
    def flip(self):
        """Gets the flip of this ShotDataOrientation.  # noqa: E501

        Invert Shot horizontally  # noqa: E501

        :return: The flip of this ShotDataOrientation.  # noqa: E501
        :rtype: bool
        """
        return self._flip

    @flip.setter
    def flip(self, flip):
        """Sets the flip of this ShotDataOrientation.

        Invert Shot horizontally  # noqa: E501

        :param flip: The flip of this ShotDataOrientation.  # noqa: E501
        :type: bool
        """

        self._flip = flip

    @property
    def flop(self):
        """Gets the flop of this ShotDataOrientation.  # noqa: E501

        Invert Shot vertically  # noqa: E501

        :return: The flop of this ShotDataOrientation.  # noqa: E501
        :rtype: bool
        """
        return self._flop

    @flop.setter
    def flop(self, flop):
        """Sets the flop of this ShotDataOrientation.

        Invert Shot vertically  # noqa: E501

        :param flop: The flop of this ShotDataOrientation.  # noqa: E501
        :type: bool
        """

        self._flop = flop

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShotDataOrientation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShotDataOrientation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
