# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShotDataFraming(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'offset': 'Vector2',
        'scale': 'Vector2',
        'rotate': 'float',
        'opacity': 'float',
        'animation': 'AnimationData'
    }

    attribute_map = {
        'offset': 'offset',
        'scale': 'scale',
        'rotate': 'rotate',
        'opacity': 'opacity',
        'animation': 'animation'
    }

    def __init__(self, offset=None, scale=None, rotate=None, opacity=None, animation=None):  # noqa: E501
        """ShotDataFraming - a model defined in Swagger"""  # noqa: E501
        self._offset = None
        self._scale = None
        self._rotate = None
        self._opacity = None
        self._animation = None
        self.discriminator = None
        if offset is not None:
            self.offset = offset
        if scale is not None:
            self.scale = scale
        if rotate is not None:
            self.rotate = rotate
        if opacity is not None:
            self.opacity = opacity
        if animation is not None:
            self.animation = animation

    @property
    def offset(self):
        """Gets the offset of this ShotDataFraming.  # noqa: E501


        :return: The offset of this ShotDataFraming.  # noqa: E501
        :rtype: Vector2
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this ShotDataFraming.


        :param offset: The offset of this ShotDataFraming.  # noqa: E501
        :type: Vector2
        """

        self._offset = offset

    @property
    def scale(self):
        """Gets the scale of this ShotDataFraming.  # noqa: E501


        :return: The scale of this ShotDataFraming.  # noqa: E501
        :rtype: Vector2
        """
        return self._scale

    @scale.setter
    def scale(self, scale):
        """Sets the scale of this ShotDataFraming.


        :param scale: The scale of this ShotDataFraming.  # noqa: E501
        :type: Vector2
        """

        self._scale = scale

    @property
    def rotate(self):
        """Gets the rotate of this ShotDataFraming.  # noqa: E501

        Rotation angle in degrees  # noqa: E501

        :return: The rotate of this ShotDataFraming.  # noqa: E501
        :rtype: float
        """
        return self._rotate

    @rotate.setter
    def rotate(self, rotate):
        """Sets the rotate of this ShotDataFraming.

        Rotation angle in degrees  # noqa: E501

        :param rotate: The rotate of this ShotDataFraming.  # noqa: E501
        :type: float
        """

        self._rotate = rotate

    @property
    def opacity(self):
        """Gets the opacity of this ShotDataFraming.  # noqa: E501

        Opacity percentage  # noqa: E501

        :return: The opacity of this ShotDataFraming.  # noqa: E501
        :rtype: float
        """
        return self._opacity

    @opacity.setter
    def opacity(self, opacity):
        """Sets the opacity of this ShotDataFraming.

        Opacity percentage  # noqa: E501

        :param opacity: The opacity of this ShotDataFraming.  # noqa: E501
        :type: float
        """

        self._opacity = opacity

    @property
    def animation(self):
        """Gets the animation of this ShotDataFraming.  # noqa: E501


        :return: The animation of this ShotDataFraming.  # noqa: E501
        :rtype: AnimationData
        """
        return self._animation

    @animation.setter
    def animation(self, animation):
        """Sets the animation of this ShotDataFraming.


        :param animation: The animation of this ShotDataFraming.  # noqa: E501
        :type: AnimationData
        """

        self._animation = animation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShotDataFraming, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShotDataFraming):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
