# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShotDataColorFormat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'colorspace': 'str',
        'eotf': 'str',
        'lut': 'str'
    }

    attribute_map = {
        'colorspace': 'colorspace',
        'eotf': 'eotf',
        'lut': 'lut'
    }

    def __init__(self, colorspace=None, eotf=None, lut=None):  # noqa: E501
        """ShotDataColorFormat - a model defined in Swagger"""  # noqa: E501
        self._colorspace = None
        self._eotf = None
        self._lut = None
        self.discriminator = None
        if colorspace is not None:
            self.colorspace = colorspace
        if eotf is not None:
            self.eotf = eotf
        if lut is not None:
            self.lut = lut

    @property
    def colorspace(self):
        """Gets the colorspace of this ShotDataColorFormat.  # noqa: E501

        Color space of the Shot  # noqa: E501

        :return: The colorspace of this ShotDataColorFormat.  # noqa: E501
        :rtype: str
        """
        return self._colorspace

    @colorspace.setter
    def colorspace(self, colorspace):
        """Sets the colorspace of this ShotDataColorFormat.

        Color space of the Shot  # noqa: E501

        :param colorspace: The colorspace of this ShotDataColorFormat.  # noqa: E501
        :type: str
        """

        self._colorspace = colorspace

    @property
    def eotf(self):
        """Gets the eotf of this ShotDataColorFormat.  # noqa: E501

        EOTF of the Shot  # noqa: E501

        :return: The eotf of this ShotDataColorFormat.  # noqa: E501
        :rtype: str
        """
        return self._eotf

    @eotf.setter
    def eotf(self, eotf):
        """Sets the eotf of this ShotDataColorFormat.

        EOTF of the Shot  # noqa: E501

        :param eotf: The eotf of this ShotDataColorFormat.  # noqa: E501
        :type: str
        """

        self._eotf = eotf

    @property
    def lut(self):
        """Gets the lut of this ShotDataColorFormat.  # noqa: E501

        LUT applied to the shot  # noqa: E501

        :return: The lut of this ShotDataColorFormat.  # noqa: E501
        :rtype: str
        """
        return self._lut

    @lut.setter
    def lut(self, lut):
        """Sets the lut of this ShotDataColorFormat.

        LUT applied to the shot  # noqa: E501

        :param lut: The lut of this ShotDataColorFormat.  # noqa: E501
        :type: str
        """

        self._lut = lut

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShotDataColorFormat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShotDataColorFormat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
