# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShotDataHandles(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_in': 'int',
        'out': 'int',
        'start': 'Timecode',
        'end': 'Timecode'
    }

    attribute_map = {
        '_in': 'in',
        'out': 'out',
        'start': 'start',
        'end': 'end'
    }

    def __init__(self, _in=None, out=None, start=None, end=None):  # noqa: E501
        """ShotDataHandles - a model defined in Swagger"""  # noqa: E501
        self.__in = None
        self._out = None
        self._start = None
        self._end = None
        self.discriminator = None
        if _in is not None:
            self._in = _in
        if out is not None:
            self.out = out
        if start is not None:
            self.start = start
        if end is not None:
            self.end = end

    @property
    def _in(self):
        """Gets the _in of this ShotDataHandles.  # noqa: E501

        In-point of the Shot  # noqa: E501

        :return: The _in of this ShotDataHandles.  # noqa: E501
        :rtype: int
        """
        return self.__in

    @_in.setter
    def _in(self, _in):
        """Sets the _in of this ShotDataHandles.

        In-point of the Shot  # noqa: E501

        :param _in: The _in of this ShotDataHandles.  # noqa: E501
        :type: int
        """

        self.__in = _in

    @property
    def out(self):
        """Gets the out of this ShotDataHandles.  # noqa: E501

        Out-point of the Shot  # noqa: E501

        :return: The out of this ShotDataHandles.  # noqa: E501
        :rtype: int
        """
        return self._out

    @out.setter
    def out(self, out):
        """Sets the out of this ShotDataHandles.

        Out-point of the Shot  # noqa: E501

        :param out: The out of this ShotDataHandles.  # noqa: E501
        :type: int
        """

        self._out = out

    @property
    def start(self):
        """Gets the start of this ShotDataHandles.  # noqa: E501


        :return: The start of this ShotDataHandles.  # noqa: E501
        :rtype: Timecode
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this ShotDataHandles.


        :param start: The start of this ShotDataHandles.  # noqa: E501
        :type: Timecode
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this ShotDataHandles.  # noqa: E501


        :return: The end of this ShotDataHandles.  # noqa: E501
        :rtype: Timecode
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this ShotDataHandles.


        :param end: The end of this ShotDataHandles.  # noqa: E501
        :type: Timecode
        """

        self._end = end

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShotDataHandles, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShotDataHandles):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
