# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShotData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'Uuid',
        'type_uuid': 'Uuid',
        'file': 'str',
        'name': 'str',
        'preset_file': 'str',
        'reel_id': 'str',
        'scene': 'str',
        'take': 'str',
        'circled': 'bool',
        'fps': 'float',
        'fps_multiplier': 'float',
        'fps_offset': 'float',
        'fps_mode': 'int',
        'frame_tc': 'int',
        'timecode': 'Timecode',
        'length': 'int',
        'handles': 'ShotDataHandles',
        'size': 'ShotDataSize',
        'aspect': 'float',
        'output': 'ShotDataOutput',
        'framing': 'ShotDataFraming',
        'view': 'ShotDataView',
        'orientation': 'ShotDataOrientation',
        'color_format': 'ShotDataColorFormat',
        'colorgrade': 'ColorgradeData',
        'camera': 'CameraData',
        'mos': 'bool',
        'audio': 'ShotDataAudio',
        'metadata': 'Metadata',
        'notes': 'list[NoteData]',
        'staging': 'StagingData',
        'inputs': 'InputsData'
    }

    attribute_map = {
        'uuid': 'uuid',
        'type_uuid': 'type_uuid',
        'file': 'file',
        'name': 'name',
        'preset_file': 'preset_file',
        'reel_id': 'reel_id',
        'scene': 'scene',
        'take': 'take',
        'circled': 'circled',
        'fps': 'fps',
        'fps_multiplier': 'fps_multiplier',
        'fps_offset': 'fps_offset',
        'fps_mode': 'fps_mode',
        'frame_tc': 'frame_tc',
        'timecode': 'timecode',
        'length': 'length',
        'handles': 'handles',
        'size': 'size',
        'aspect': 'aspect',
        'output': 'output',
        'framing': 'framing',
        'view': 'view',
        'orientation': 'orientation',
        'color_format': 'color_format',
        'colorgrade': 'colorgrade',
        'camera': 'camera',
        'mos': 'mos',
        'audio': 'audio',
        'metadata': 'metadata',
        'notes': 'notes',
        'staging': 'staging',
        'inputs': 'inputs'
    }

    def __init__(self, uuid=None, type_uuid=None, file=None, name=None, preset_file=None, reel_id=None, scene=None, take=None, circled=None, fps=None, fps_multiplier=None, fps_offset=None, fps_mode=None, frame_tc=None, timecode=None, length=None, handles=None, size=None, aspect=None, output=None, framing=None, view=None, orientation=None, color_format=None, colorgrade=None, camera=None, mos=None, audio=None, metadata=None, notes=None, staging=None, inputs=None):  # noqa: E501
        """ShotData - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._type_uuid = None
        self._file = None
        self._name = None
        self._preset_file = None
        self._reel_id = None
        self._scene = None
        self._take = None
        self._circled = None
        self._fps = None
        self._fps_multiplier = None
        self._fps_offset = None
        self._fps_mode = None
        self._frame_tc = None
        self._timecode = None
        self._length = None
        self._handles = None
        self._size = None
        self._aspect = None
        self._output = None
        self._framing = None
        self._view = None
        self._orientation = None
        self._color_format = None
        self._colorgrade = None
        self._camera = None
        self._mos = None
        self._audio = None
        self._metadata = None
        self._notes = None
        self._staging = None
        self._inputs = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if type_uuid is not None:
            self.type_uuid = type_uuid
        if file is not None:
            self.file = file
        if name is not None:
            self.name = name
        if preset_file is not None:
            self.preset_file = preset_file
        if reel_id is not None:
            self.reel_id = reel_id
        if scene is not None:
            self.scene = scene
        if take is not None:
            self.take = take
        if circled is not None:
            self.circled = circled
        if fps is not None:
            self.fps = fps
        if fps_multiplier is not None:
            self.fps_multiplier = fps_multiplier
        if fps_offset is not None:
            self.fps_offset = fps_offset
        if fps_mode is not None:
            self.fps_mode = fps_mode
        if frame_tc is not None:
            self.frame_tc = frame_tc
        if timecode is not None:
            self.timecode = timecode
        if length is not None:
            self.length = length
        if handles is not None:
            self.handles = handles
        if size is not None:
            self.size = size
        if aspect is not None:
            self.aspect = aspect
        if output is not None:
            self.output = output
        if framing is not None:
            self.framing = framing
        if view is not None:
            self.view = view
        if orientation is not None:
            self.orientation = orientation
        if color_format is not None:
            self.color_format = color_format
        if colorgrade is not None:
            self.colorgrade = colorgrade
        if camera is not None:
            self.camera = camera
        if mos is not None:
            self.mos = mos
        if audio is not None:
            self.audio = audio
        if metadata is not None:
            self.metadata = metadata
        if notes is not None:
            self.notes = notes
        if staging is not None:
            self.staging = staging
        if inputs is not None:
            self.inputs = inputs

    @property
    def uuid(self):
        """Gets the uuid of this ShotData.  # noqa: E501


        :return: The uuid of this ShotData.  # noqa: E501
        :rtype: Uuid
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ShotData.


        :param uuid: The uuid of this ShotData.  # noqa: E501
        :type: Uuid
        """

        self._uuid = uuid

    @property
    def type_uuid(self):
        """Gets the type_uuid of this ShotData.  # noqa: E501


        :return: The type_uuid of this ShotData.  # noqa: E501
        :rtype: Uuid
        """
        return self._type_uuid

    @type_uuid.setter
    def type_uuid(self, type_uuid):
        """Sets the type_uuid of this ShotData.


        :param type_uuid: The type_uuid of this ShotData.  # noqa: E501
        :type: Uuid
        """

        self._type_uuid = type_uuid

    @property
    def file(self):
        """Gets the file of this ShotData.  # noqa: E501

        Full filename of the Shot media  # noqa: E501

        :return: The file of this ShotData.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this ShotData.

        Full filename of the Shot media  # noqa: E501

        :param file: The file of this ShotData.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def name(self):
        """Gets the name of this ShotData.  # noqa: E501

        Name of the Shot  # noqa: E501

        :return: The name of this ShotData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ShotData.

        Name of the Shot  # noqa: E501

        :param name: The name of this ShotData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def preset_file(self):
        """Gets the preset_file of this ShotData.  # noqa: E501

        File path to the preset file (input only).  # noqa: E501

        :return: The preset_file of this ShotData.  # noqa: E501
        :rtype: str
        """
        return self._preset_file

    @preset_file.setter
    def preset_file(self, preset_file):
        """Sets the preset_file of this ShotData.

        File path to the preset file (input only).  # noqa: E501

        :param preset_file: The preset_file of this ShotData.  # noqa: E501
        :type: str
        """

        self._preset_file = preset_file

    @property
    def reel_id(self):
        """Gets the reel_id of this ShotData.  # noqa: E501

        Reel identifier  # noqa: E501

        :return: The reel_id of this ShotData.  # noqa: E501
        :rtype: str
        """
        return self._reel_id

    @reel_id.setter
    def reel_id(self, reel_id):
        """Sets the reel_id of this ShotData.

        Reel identifier  # noqa: E501

        :param reel_id: The reel_id of this ShotData.  # noqa: E501
        :type: str
        """

        self._reel_id = reel_id

    @property
    def scene(self):
        """Gets the scene of this ShotData.  # noqa: E501

        Scene identifier  # noqa: E501

        :return: The scene of this ShotData.  # noqa: E501
        :rtype: str
        """
        return self._scene

    @scene.setter
    def scene(self, scene):
        """Sets the scene of this ShotData.

        Scene identifier  # noqa: E501

        :param scene: The scene of this ShotData.  # noqa: E501
        :type: str
        """

        self._scene = scene

    @property
    def take(self):
        """Gets the take of this ShotData.  # noqa: E501

        Take identifier  # noqa: E501

        :return: The take of this ShotData.  # noqa: E501
        :rtype: str
        """
        return self._take

    @take.setter
    def take(self, take):
        """Sets the take of this ShotData.

        Take identifier  # noqa: E501

        :param take: The take of this ShotData.  # noqa: E501
        :type: str
        """

        self._take = take

    @property
    def circled(self):
        """Gets the circled of this ShotData.  # noqa: E501

        Circle Shot y/n  # noqa: E501

        :return: The circled of this ShotData.  # noqa: E501
        :rtype: bool
        """
        return self._circled

    @circled.setter
    def circled(self, circled):
        """Sets the circled of this ShotData.

        Circle Shot y/n  # noqa: E501

        :param circled: The circled of this ShotData.  # noqa: E501
        :type: bool
        """

        self._circled = circled

    @property
    def fps(self):
        """Gets the fps of this ShotData.  # noqa: E501

        Frames per second of the shot  # noqa: E501

        :return: The fps of this ShotData.  # noqa: E501
        :rtype: float
        """
        return self._fps

    @fps.setter
    def fps(self, fps):
        """Sets the fps of this ShotData.

        Frames per second of the shot  # noqa: E501

        :param fps: The fps of this ShotData.  # noqa: E501
        :type: float
        """

        self._fps = fps

    @property
    def fps_multiplier(self):
        """Gets the fps_multiplier of this ShotData.  # noqa: E501

        FPS multiplier for retiming  # noqa: E501

        :return: The fps_multiplier of this ShotData.  # noqa: E501
        :rtype: float
        """
        return self._fps_multiplier

    @fps_multiplier.setter
    def fps_multiplier(self, fps_multiplier):
        """Sets the fps_multiplier of this ShotData.

        FPS multiplier for retiming  # noqa: E501

        :param fps_multiplier: The fps_multiplier of this ShotData.  # noqa: E501
        :type: float
        """

        self._fps_multiplier = fps_multiplier

    @property
    def fps_offset(self):
        """Gets the fps_offset of this ShotData.  # noqa: E501

        FPS offset for retiming  # noqa: E501

        :return: The fps_offset of this ShotData.  # noqa: E501
        :rtype: float
        """
        return self._fps_offset

    @fps_offset.setter
    def fps_offset(self, fps_offset):
        """Sets the fps_offset of this ShotData.

        FPS offset for retiming  # noqa: E501

        :param fps_offset: The fps_offset of this ShotData.  # noqa: E501
        :type: float
        """

        self._fps_offset = fps_offset

    @property
    def fps_mode(self):
        """Gets the fps_mode of this ShotData.  # noqa: E501

        FPS mode for retiming (0 = Nearest Frame, 1 = Rolling Mix)  # noqa: E501

        :return: The fps_mode of this ShotData.  # noqa: E501
        :rtype: int
        """
        return self._fps_mode

    @fps_mode.setter
    def fps_mode(self, fps_mode):
        """Sets the fps_mode of this ShotData.

        FPS mode for retiming (0 = Nearest Frame, 1 = Rolling Mix)  # noqa: E501

        :param fps_mode: The fps_mode of this ShotData.  # noqa: E501
        :type: int
        """

        self._fps_mode = fps_mode

    @property
    def frame_tc(self):
        """Gets the frame_tc of this ShotData.  # noqa: E501

        Frame number of the Shot timecode  # noqa: E501

        :return: The frame_tc of this ShotData.  # noqa: E501
        :rtype: int
        """
        return self._frame_tc

    @frame_tc.setter
    def frame_tc(self, frame_tc):
        """Sets the frame_tc of this ShotData.

        Frame number of the Shot timecode  # noqa: E501

        :param frame_tc: The frame_tc of this ShotData.  # noqa: E501
        :type: int
        """

        self._frame_tc = frame_tc

    @property
    def timecode(self):
        """Gets the timecode of this ShotData.  # noqa: E501


        :return: The timecode of this ShotData.  # noqa: E501
        :rtype: Timecode
        """
        return self._timecode

    @timecode.setter
    def timecode(self, timecode):
        """Sets the timecode of this ShotData.


        :param timecode: The timecode of this ShotData.  # noqa: E501
        :type: Timecode
        """

        self._timecode = timecode

    @property
    def length(self):
        """Gets the length of this ShotData.  # noqa: E501

        Length of the Shot in frames  # noqa: E501

        :return: The length of this ShotData.  # noqa: E501
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this ShotData.

        Length of the Shot in frames  # noqa: E501

        :param length: The length of this ShotData.  # noqa: E501
        :type: int
        """

        self._length = length

    @property
    def handles(self):
        """Gets the handles of this ShotData.  # noqa: E501


        :return: The handles of this ShotData.  # noqa: E501
        :rtype: ShotDataHandles
        """
        return self._handles

    @handles.setter
    def handles(self, handles):
        """Sets the handles of this ShotData.


        :param handles: The handles of this ShotData.  # noqa: E501
        :type: ShotDataHandles
        """

        self._handles = handles

    @property
    def size(self):
        """Gets the size of this ShotData.  # noqa: E501


        :return: The size of this ShotData.  # noqa: E501
        :rtype: ShotDataSize
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this ShotData.


        :param size: The size of this ShotData.  # noqa: E501
        :type: ShotDataSize
        """

        self._size = size

    @property
    def aspect(self):
        """Gets the aspect of this ShotData.  # noqa: E501

        Aspect ratio of the Shot  # noqa: E501

        :return: The aspect of this ShotData.  # noqa: E501
        :rtype: float
        """
        return self._aspect

    @aspect.setter
    def aspect(self, aspect):
        """Sets the aspect of this ShotData.

        Aspect ratio of the Shot  # noqa: E501

        :param aspect: The aspect of this ShotData.  # noqa: E501
        :type: float
        """

        self._aspect = aspect

    @property
    def output(self):
        """Gets the output of this ShotData.  # noqa: E501


        :return: The output of this ShotData.  # noqa: E501
        :rtype: ShotDataOutput
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this ShotData.


        :param output: The output of this ShotData.  # noqa: E501
        :type: ShotDataOutput
        """

        self._output = output

    @property
    def framing(self):
        """Gets the framing of this ShotData.  # noqa: E501


        :return: The framing of this ShotData.  # noqa: E501
        :rtype: ShotDataFraming
        """
        return self._framing

    @framing.setter
    def framing(self, framing):
        """Sets the framing of this ShotData.


        :param framing: The framing of this ShotData.  # noqa: E501
        :type: ShotDataFraming
        """

        self._framing = framing

    @property
    def view(self):
        """Gets the view of this ShotData.  # noqa: E501


        :return: The view of this ShotData.  # noqa: E501
        :rtype: ShotDataView
        """
        return self._view

    @view.setter
    def view(self, view):
        """Sets the view of this ShotData.


        :param view: The view of this ShotData.  # noqa: E501
        :type: ShotDataView
        """

        self._view = view

    @property
    def orientation(self):
        """Gets the orientation of this ShotData.  # noqa: E501


        :return: The orientation of this ShotData.  # noqa: E501
        :rtype: ShotDataOrientation
        """
        return self._orientation

    @orientation.setter
    def orientation(self, orientation):
        """Sets the orientation of this ShotData.


        :param orientation: The orientation of this ShotData.  # noqa: E501
        :type: ShotDataOrientation
        """

        self._orientation = orientation

    @property
    def color_format(self):
        """Gets the color_format of this ShotData.  # noqa: E501


        :return: The color_format of this ShotData.  # noqa: E501
        :rtype: ShotDataColorFormat
        """
        return self._color_format

    @color_format.setter
    def color_format(self, color_format):
        """Sets the color_format of this ShotData.


        :param color_format: The color_format of this ShotData.  # noqa: E501
        :type: ShotDataColorFormat
        """

        self._color_format = color_format

    @property
    def colorgrade(self):
        """Gets the colorgrade of this ShotData.  # noqa: E501


        :return: The colorgrade of this ShotData.  # noqa: E501
        :rtype: ColorgradeData
        """
        return self._colorgrade

    @colorgrade.setter
    def colorgrade(self, colorgrade):
        """Sets the colorgrade of this ShotData.


        :param colorgrade: The colorgrade of this ShotData.  # noqa: E501
        :type: ColorgradeData
        """

        self._colorgrade = colorgrade

    @property
    def camera(self):
        """Gets the camera of this ShotData.  # noqa: E501


        :return: The camera of this ShotData.  # noqa: E501
        :rtype: CameraData
        """
        return self._camera

    @camera.setter
    def camera(self, camera):
        """Sets the camera of this ShotData.


        :param camera: The camera of this ShotData.  # noqa: E501
        :type: CameraData
        """

        self._camera = camera

    @property
    def mos(self):
        """Gets the mos of this ShotData.  # noqa: E501

        Mit Ohne Sound Shot  # noqa: E501

        :return: The mos of this ShotData.  # noqa: E501
        :rtype: bool
        """
        return self._mos

    @mos.setter
    def mos(self, mos):
        """Sets the mos of this ShotData.

        Mit Ohne Sound Shot  # noqa: E501

        :param mos: The mos of this ShotData.  # noqa: E501
        :type: bool
        """

        self._mos = mos

    @property
    def audio(self):
        """Gets the audio of this ShotData.  # noqa: E501


        :return: The audio of this ShotData.  # noqa: E501
        :rtype: ShotDataAudio
        """
        return self._audio

    @audio.setter
    def audio(self, audio):
        """Sets the audio of this ShotData.


        :param audio: The audio of this ShotData.  # noqa: E501
        :type: ShotDataAudio
        """

        self._audio = audio

    @property
    def metadata(self):
        """Gets the metadata of this ShotData.  # noqa: E501


        :return: The metadata of this ShotData.  # noqa: E501
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this ShotData.


        :param metadata: The metadata of this ShotData.  # noqa: E501
        :type: Metadata
        """

        self._metadata = metadata

    @property
    def notes(self):
        """Gets the notes of this ShotData.  # noqa: E501

        Notes of the Shot  # noqa: E501

        :return: The notes of this ShotData.  # noqa: E501
        :rtype: list[NoteData]
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this ShotData.

        Notes of the Shot  # noqa: E501

        :param notes: The notes of this ShotData.  # noqa: E501
        :type: list[NoteData]
        """

        self._notes = notes

    @property
    def staging(self):
        """Gets the staging of this ShotData.  # noqa: E501


        :return: The staging of this ShotData.  # noqa: E501
        :rtype: StagingData
        """
        return self._staging

    @staging.setter
    def staging(self, staging):
        """Sets the staging of this ShotData.


        :param staging: The staging of this ShotData.  # noqa: E501
        :type: StagingData
        """

        self._staging = staging

    @property
    def inputs(self):
        """Gets the inputs of this ShotData.  # noqa: E501


        :return: The inputs of this ShotData.  # noqa: E501
        :rtype: InputsData
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this ShotData.


        :param inputs: The inputs of this ShotData.  # noqa: E501
        :type: InputsData
        """

        self._inputs = inputs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShotData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShotData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
