# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SlotData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'length': 'int',
        'auto_length': 'bool',
        'shots': 'list[ShotData]',
        'smode': 'str',
        'timecode': 'Timecode',
        'transition': 'SlotDataTransition'
    }

    attribute_map = {
        'name': 'name',
        'length': 'length',
        'auto_length': 'auto_length',
        'shots': 'shots',
        'smode': 'smode',
        'timecode': 'timecode',
        'transition': 'transition'
    }

    def __init__(self, name=None, length=None, auto_length=None, shots=None, smode=None, timecode=None, transition=None):  # noqa: E501
        """SlotData - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._length = None
        self._auto_length = None
        self._shots = None
        self._smode = None
        self._timecode = None
        self._transition = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if length is not None:
            self.length = length
        if auto_length is not None:
            self.auto_length = auto_length
        if shots is not None:
            self.shots = shots
        if smode is not None:
            self.smode = smode
        if timecode is not None:
            self.timecode = timecode
        if transition is not None:
            self.transition = transition

    @property
    def name(self):
        """Gets the name of this SlotData.  # noqa: E501

        Name of the slot  # noqa: E501

        :return: The name of this SlotData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SlotData.

        Name of the slot  # noqa: E501

        :param name: The name of this SlotData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def length(self):
        """Gets the length of this SlotData.  # noqa: E501

        Length of the Slot in frames. A Slot can have a length independant of the Shot in it.  # noqa: E501

        :return: The length of this SlotData.  # noqa: E501
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this SlotData.

        Length of the Slot in frames. A Slot can have a length independant of the Shot in it.  # noqa: E501

        :param length: The length of this SlotData.  # noqa: E501
        :type: int
        """

        self._length = length

    @property
    def auto_length(self):
        """Gets the auto_length of this SlotData.  # noqa: E501

        By default a Slot adopts its length to the shots it contains. Once edited, the Slot length is maintained.  # noqa: E501

        :return: The auto_length of this SlotData.  # noqa: E501
        :rtype: bool
        """
        return self._auto_length

    @auto_length.setter
    def auto_length(self, auto_length):
        """Sets the auto_length of this SlotData.

        By default a Slot adopts its length to the shots it contains. Once edited, the Slot length is maintained.  # noqa: E501

        :param auto_length: The auto_length of this SlotData.  # noqa: E501
        :type: bool
        """

        self._auto_length = auto_length

    @property
    def shots(self):
        """Gets the shots of this SlotData.  # noqa: E501


        :return: The shots of this SlotData.  # noqa: E501
        :rtype: list[ShotData]
        """
        return self._shots

    @shots.setter
    def shots(self, shots):
        """Sets the shots of this SlotData.


        :param shots: The shots of this SlotData.  # noqa: E501
        :type: list[ShotData]
        """

        self._shots = shots

    @property
    def smode(self):
        """Gets the smode of this SlotData.  # noqa: E501

        Slot playmode in case the Slot length differs from the Shot length.  # noqa: E501

        :return: The smode of this SlotData.  # noqa: E501
        :rtype: str
        """
        return self._smode

    @smode.setter
    def smode(self, smode):
        """Sets the smode of this SlotData.

        Slot playmode in case the Slot length differs from the Shot length.  # noqa: E501

        :param smode: The smode of this SlotData.  # noqa: E501
        :type: str
        """
        allowed_values = ["Once", "Loop", "Bounce", "Reverse", "RLoop", "RBounce"]  # noqa: E501
        if smode not in allowed_values:
            raise ValueError(
                "Invalid value for `smode` ({0}), must be one of {1}"  # noqa: E501
                .format(smode, allowed_values)
            )

        self._smode = smode

    @property
    def timecode(self):
        """Gets the timecode of this SlotData.  # noqa: E501


        :return: The timecode of this SlotData.  # noqa: E501
        :rtype: Timecode
        """
        return self._timecode

    @timecode.setter
    def timecode(self, timecode):
        """Sets the timecode of this SlotData.


        :param timecode: The timecode of this SlotData.  # noqa: E501
        :type: Timecode
        """

        self._timecode = timecode

    @property
    def transition(self):
        """Gets the transition of this SlotData.  # noqa: E501


        :return: The transition of this SlotData.  # noqa: E501
        :rtype: SlotDataTransition
        """
        return self._transition

    @transition.setter
    def transition(self, transition):
        """Sets the transition of this SlotData.


        :param transition: The transition of this SlotData.  # noqa: E501
        :type: SlotDataTransition
        """

        self._transition = transition

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SlotData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SlotData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
