# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SlotDataTransition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'after': 'int',
        'before': 'int',
        'type': 'str',
        'wipe': 'int',
        'reverse': 'bool',
        'dist': 'float',
        'gamma_neutral': 'bool'
    }

    attribute_map = {
        'after': 'after',
        'before': 'before',
        'type': 'type',
        'wipe': 'wipe',
        'reverse': 'reverse',
        'dist': 'dist',
        'gamma_neutral': 'gamma_neutral'
    }

    def __init__(self, after=None, before=None, type=None, wipe=None, reverse=None, dist=None, gamma_neutral=None):  # noqa: E501
        """SlotDataTransition - a model defined in Swagger"""  # noqa: E501
        self._after = None
        self._before = None
        self._type = None
        self._wipe = None
        self._reverse = None
        self._dist = None
        self._gamma_neutral = None
        self.discriminator = None
        self.after = after
        self.before = before
        self.type = type
        if wipe is not None:
            self.wipe = wipe
        if reverse is not None:
            self.reverse = reverse
        if dist is not None:
            self.dist = dist
        if gamma_neutral is not None:
            self.gamma_neutral = gamma_neutral

    @property
    def after(self):
        """Gets the after of this SlotDataTransition.  # noqa: E501

        number of frames the transition covers after the cut  # noqa: E501

        :return: The after of this SlotDataTransition.  # noqa: E501
        :rtype: int
        """
        return self._after

    @after.setter
    def after(self, after):
        """Sets the after of this SlotDataTransition.

        number of frames the transition covers after the cut  # noqa: E501

        :param after: The after of this SlotDataTransition.  # noqa: E501
        :type: int
        """
        if after is None:
            raise ValueError("Invalid value for `after`, must not be `None`")  # noqa: E501

        self._after = after

    @property
    def before(self):
        """Gets the before of this SlotDataTransition.  # noqa: E501

        number of frames the transition covers before the cut  # noqa: E501

        :return: The before of this SlotDataTransition.  # noqa: E501
        :rtype: int
        """
        return self._before

    @before.setter
    def before(self, before):
        """Sets the before of this SlotDataTransition.

        number of frames the transition covers before the cut  # noqa: E501

        :param before: The before of this SlotDataTransition.  # noqa: E501
        :type: int
        """
        if before is None:
            raise ValueError("Invalid value for `before`, must not be `None`")  # noqa: E501

        self._before = before

    @property
    def type(self):
        """Gets the type of this SlotDataTransition.  # noqa: E501

        Type of transition  # noqa: E501

        :return: The type of this SlotDataTransition.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SlotDataTransition.

        Type of transition  # noqa: E501

        :param type: The type of this SlotDataTransition.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def wipe(self):
        """Gets the wipe of this SlotDataTransition.  # noqa: E501

        Wipe sub-type when main transition type is set to Wipe  # noqa: E501

        :return: The wipe of this SlotDataTransition.  # noqa: E501
        :rtype: int
        """
        return self._wipe

    @wipe.setter
    def wipe(self, wipe):
        """Sets the wipe of this SlotDataTransition.

        Wipe sub-type when main transition type is set to Wipe  # noqa: E501

        :param wipe: The wipe of this SlotDataTransition.  # noqa: E501
        :type: int
        """

        self._wipe = wipe

    @property
    def reverse(self):
        """Gets the reverse of this SlotDataTransition.  # noqa: E501

        Whether the transition is reversed  # noqa: E501

        :return: The reverse of this SlotDataTransition.  # noqa: E501
        :rtype: bool
        """
        return self._reverse

    @reverse.setter
    def reverse(self, reverse):
        """Sets the reverse of this SlotDataTransition.

        Whether the transition is reversed  # noqa: E501

        :param reverse: The reverse of this SlotDataTransition.  # noqa: E501
        :type: bool
        """

        self._reverse = reverse

    @property
    def dist(self):
        """Gets the dist of this SlotDataTransition.  # noqa: E501

        Distance in pixels that will be smoothed of between shots  # noqa: E501

        :return: The dist of this SlotDataTransition.  # noqa: E501
        :rtype: float
        """
        return self._dist

    @dist.setter
    def dist(self, dist):
        """Sets the dist of this SlotDataTransition.

        Distance in pixels that will be smoothed of between shots  # noqa: E501

        :param dist: The dist of this SlotDataTransition.  # noqa: E501
        :type: float
        """

        self._dist = dist

    @property
    def gamma_neutral(self):
        """Gets the gamma_neutral of this SlotDataTransition.  # noqa: E501

        Use a gamma neutral transition  # noqa: E501

        :return: The gamma_neutral of this SlotDataTransition.  # noqa: E501
        :rtype: bool
        """
        return self._gamma_neutral

    @gamma_neutral.setter
    def gamma_neutral(self, gamma_neutral):
        """Sets the gamma_neutral of this SlotDataTransition.

        Use a gamma neutral transition  # noqa: E501

        :param gamma_neutral: The gamma_neutral of this SlotDataTransition.  # noqa: E501
        :type: bool
        """

        self._gamma_neutral = gamma_neutral

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SlotDataTransition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SlotDataTransition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
