# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StagingDataInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stage_shot_uuid': 'Uuid',
        'shot': 'ShotData'
    }

    attribute_map = {
        'stage_shot_uuid': 'stage_shot_uuid',
        'shot': 'shot'
    }

    def __init__(self, stage_shot_uuid=None, shot=None):  # noqa: E501
        """StagingDataInner - a model defined in Swagger"""  # noqa: E501
        self._stage_shot_uuid = None
        self._shot = None
        self.discriminator = None
        if stage_shot_uuid is not None:
            self.stage_shot_uuid = stage_shot_uuid
        if shot is not None:
            self.shot = shot

    @property
    def stage_shot_uuid(self):
        """Gets the stage_shot_uuid of this StagingDataInner.  # noqa: E501


        :return: The stage_shot_uuid of this StagingDataInner.  # noqa: E501
        :rtype: Uuid
        """
        return self._stage_shot_uuid

    @stage_shot_uuid.setter
    def stage_shot_uuid(self, stage_shot_uuid):
        """Sets the stage_shot_uuid of this StagingDataInner.


        :param stage_shot_uuid: The stage_shot_uuid of this StagingDataInner.  # noqa: E501
        :type: Uuid
        """

        self._stage_shot_uuid = stage_shot_uuid

    @property
    def shot(self):
        """Gets the shot of this StagingDataInner.  # noqa: E501


        :return: The shot of this StagingDataInner.  # noqa: E501
        :rtype: ShotData
        """
        return self._shot

    @shot.setter
    def shot(self, shot):
        """Sets the shot of this StagingDataInner.


        :param shot: The shot of this StagingDataInner.  # noqa: E501
        :type: ShotData
        """

        self._shot = shot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StagingDataInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StagingDataInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
