# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SystemData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'build': 'str',
        'rest_version': 'str',
        'system_name': 'str',
        'users_folder': 'str',
        'projects_folder': 'str',
        'shared_folder': 'str',
        'http_server_ip': 'str',
        'http_server_port': 'int',
        'http_server_auto_start': 'bool'
    }

    attribute_map = {
        'version': 'version',
        'build': 'build',
        'rest_version': 'rest_version',
        'system_name': 'system_name',
        'users_folder': 'users_folder',
        'projects_folder': 'projects_folder',
        'shared_folder': 'shared_folder',
        'http_server_ip': 'http_server_ip',
        'http_server_port': 'http_server_port',
        'http_server_auto_start': 'http_server_auto_start'
    }

    def __init__(self, version=None, build=None, rest_version=None, system_name=None, users_folder=None, projects_folder=None, shared_folder=None, http_server_ip=None, http_server_port=None, http_server_auto_start=None):  # noqa: E501
        """SystemData - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._build = None
        self._rest_version = None
        self._system_name = None
        self._users_folder = None
        self._projects_folder = None
        self._shared_folder = None
        self._http_server_ip = None
        self._http_server_port = None
        self._http_server_auto_start = None
        self.discriminator = None
        if version is not None:
            self.version = version
        if build is not None:
            self.build = build
        if rest_version is not None:
            self.rest_version = rest_version
        if system_name is not None:
            self.system_name = system_name
        if users_folder is not None:
            self.users_folder = users_folder
        if projects_folder is not None:
            self.projects_folder = projects_folder
        if shared_folder is not None:
            self.shared_folder = shared_folder
        if http_server_ip is not None:
            self.http_server_ip = http_server_ip
        if http_server_port is not None:
            self.http_server_port = http_server_port
        if http_server_auto_start is not None:
            self.http_server_auto_start = http_server_auto_start

    @property
    def version(self):
        """Gets the version of this SystemData.  # noqa: E501

        Software version (readonly)  # noqa: E501

        :return: The version of this SystemData.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this SystemData.

        Software version (readonly)  # noqa: E501

        :param version: The version of this SystemData.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def build(self):
        """Gets the build of this SystemData.  # noqa: E501

        Software build number (readonly)  # noqa: E501

        :return: The build of this SystemData.  # noqa: E501
        :rtype: str
        """
        return self._build

    @build.setter
    def build(self, build):
        """Sets the build of this SystemData.

        Software build number (readonly)  # noqa: E501

        :param build: The build of this SystemData.  # noqa: E501
        :type: str
        """

        self._build = build

    @property
    def rest_version(self):
        """Gets the rest_version of this SystemData.  # noqa: E501

        REST API version (readonly)  # noqa: E501

        :return: The rest_version of this SystemData.  # noqa: E501
        :rtype: str
        """
        return self._rest_version

    @rest_version.setter
    def rest_version(self, rest_version):
        """Sets the rest_version of this SystemData.

        REST API version (readonly)  # noqa: E501

        :param rest_version: The rest_version of this SystemData.  # noqa: E501
        :type: str
        """

        self._rest_version = rest_version

    @property
    def system_name(self):
        """Gets the system_name of this SystemData.  # noqa: E501

        System name  # noqa: E501

        :return: The system_name of this SystemData.  # noqa: E501
        :rtype: str
        """
        return self._system_name

    @system_name.setter
    def system_name(self, system_name):
        """Sets the system_name of this SystemData.

        System name  # noqa: E501

        :param system_name: The system_name of this SystemData.  # noqa: E501
        :type: str
        """

        self._system_name = system_name

    @property
    def users_folder(self):
        """Gets the users_folder of this SystemData.  # noqa: E501

        Location for user profiles  # noqa: E501

        :return: The users_folder of this SystemData.  # noqa: E501
        :rtype: str
        """
        return self._users_folder

    @users_folder.setter
    def users_folder(self, users_folder):
        """Sets the users_folder of this SystemData.

        Location for user profiles  # noqa: E501

        :param users_folder: The users_folder of this SystemData.  # noqa: E501
        :type: str
        """

        self._users_folder = users_folder

    @property
    def projects_folder(self):
        """Gets the projects_folder of this SystemData.  # noqa: E501

        Location for projects  # noqa: E501

        :return: The projects_folder of this SystemData.  # noqa: E501
        :rtype: str
        """
        return self._projects_folder

    @projects_folder.setter
    def projects_folder(self, projects_folder):
        """Sets the projects_folder of this SystemData.

        Location for projects  # noqa: E501

        :param projects_folder: The projects_folder of this SystemData.  # noqa: E501
        :type: str
        """

        self._projects_folder = projects_folder

    @property
    def shared_folder(self):
        """Gets the shared_folder of this SystemData.  # noqa: E501

        Location for shared galleries  # noqa: E501

        :return: The shared_folder of this SystemData.  # noqa: E501
        :rtype: str
        """
        return self._shared_folder

    @shared_folder.setter
    def shared_folder(self, shared_folder):
        """Sets the shared_folder of this SystemData.

        Location for shared galleries  # noqa: E501

        :param shared_folder: The shared_folder of this SystemData.  # noqa: E501
        :type: str
        """

        self._shared_folder = shared_folder

    @property
    def http_server_ip(self):
        """Gets the http_server_ip of this SystemData.  # noqa: E501

        IP address of the HTTP server  # noqa: E501

        :return: The http_server_ip of this SystemData.  # noqa: E501
        :rtype: str
        """
        return self._http_server_ip

    @http_server_ip.setter
    def http_server_ip(self, http_server_ip):
        """Sets the http_server_ip of this SystemData.

        IP address of the HTTP server  # noqa: E501

        :param http_server_ip: The http_server_ip of this SystemData.  # noqa: E501
        :type: str
        """

        self._http_server_ip = http_server_ip

    @property
    def http_server_port(self):
        """Gets the http_server_port of this SystemData.  # noqa: E501

        Port number of the HTTP server  # noqa: E501

        :return: The http_server_port of this SystemData.  # noqa: E501
        :rtype: int
        """
        return self._http_server_port

    @http_server_port.setter
    def http_server_port(self, http_server_port):
        """Sets the http_server_port of this SystemData.

        Port number of the HTTP server  # noqa: E501

        :param http_server_port: The http_server_port of this SystemData.  # noqa: E501
        :type: int
        """

        self._http_server_port = http_server_port

    @property
    def http_server_auto_start(self):
        """Gets the http_server_auto_start of this SystemData.  # noqa: E501

        Start the HTTP server automatically startup of the application  # noqa: E501

        :return: The http_server_auto_start of this SystemData.  # noqa: E501
        :rtype: bool
        """
        return self._http_server_auto_start

    @http_server_auto_start.setter
    def http_server_auto_start(self, http_server_auto_start):
        """Sets the http_server_auto_start of this SystemData.

        Start the HTTP server automatically startup of the application  # noqa: E501

        :param http_server_auto_start: The http_server_auto_start of this SystemData.  # noqa: E501
        :type: bool
        """

        self._http_server_auto_start = http_server_auto_start

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
