# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserDataGearing(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'normal': 'float',
        'shift': 'float'
    }

    attribute_map = {
        'normal': 'normal',
        'shift': 'shift'
    }

    def __init__(self, normal=None, shift=None):  # noqa: E501
        """UserDataGearing - a model defined in Swagger"""  # noqa: E501
        self._normal = None
        self._shift = None
        self.discriminator = None
        if normal is not None:
            self.normal = normal
        if shift is not None:
            self.shift = shift

    @property
    def normal(self):
        """Gets the normal of this UserDataGearing.  # noqa: E501

        Normal control gearing sensitivity determine the in/decrement speed of (numeric) controls on a drag gesture  # noqa: E501

        :return: The normal of this UserDataGearing.  # noqa: E501
        :rtype: float
        """
        return self._normal

    @normal.setter
    def normal(self, normal):
        """Sets the normal of this UserDataGearing.

        Normal control gearing sensitivity determine the in/decrement speed of (numeric) controls on a drag gesture  # noqa: E501

        :param normal: The normal of this UserDataGearing.  # noqa: E501
        :type: float
        """

        self._normal = normal

    @property
    def shift(self):
        """Gets the shift of this UserDataGearing.  # noqa: E501

        The gearing sensitivity for (numeric) controls when holding down the shift key to allow for finer control  # noqa: E501

        :return: The shift of this UserDataGearing.  # noqa: E501
        :rtype: float
        """
        return self._shift

    @shift.setter
    def shift(self, shift):
        """Sets the shift of this UserDataGearing.

        The gearing sensitivity for (numeric) controls when holding down the shift key to allow for finer control  # noqa: E501

        :param shift: The shift of this UserDataGearing.  # noqa: E501
        :type: float
        """

        self._shift = shift

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserDataGearing, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserDataGearing):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
