# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from assimilate_client.api_client import ApiClient


class ApplicationApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_application_render_queue_item(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Add  # noqa: E501

        Add the Output with UUID as Item to the Render Queue. Returns an error is the item is not found or not a valid output node.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_application_render_queue_item(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: RenderQueueItem
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_application_render_queue_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.add_application_render_queue_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
            return data

    def add_application_render_queue_item_with_http_info(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Add  # noqa: E501

        Add the Output with UUID as Item to the Render Queue. Returns an error is the item is not found or not a valid output node.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_application_render_queue_item_with_http_info(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: RenderQueueItem
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_application_render_queue_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_uuid' is set
        if ('output_uuid' not in params or
                params['output_uuid'] is None):
            raise ValueError("Missing the required parameter `output_uuid` when calling `add_application_render_queue_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'output_uuid' in params:
            path_params['output_UUID'] = params['output_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/{output_UUID}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RenderQueueItem',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_application_render_queue_item_start(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Add Start  # noqa: E501

        Add the Output with UUID as Item to the Render Queue and start rendering it. Returns an error is the Output is not found or not a valid Output.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_application_render_queue_item_start(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :param DeleteMediaData body: json with delete_existing_media boolean
        :return: RenderQueueItem
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_application_render_queue_item_start_with_http_info(output_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.add_application_render_queue_item_start_with_http_info(output_uuid, **kwargs)  # noqa: E501
            return data

    def add_application_render_queue_item_start_with_http_info(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Add Start  # noqa: E501

        Add the Output with UUID as Item to the Render Queue and start rendering it. Returns an error is the Output is not found or not a valid Output.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_application_render_queue_item_start_with_http_info(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :param DeleteMediaData body: json with delete_existing_media boolean
        :return: RenderQueueItem
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_uuid', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_application_render_queue_item_start" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_uuid' is set
        if ('output_uuid' not in params or
                params['output_uuid'] is None):
            raise ValueError("Missing the required parameter `output_uuid` when calling `add_application_render_queue_item_start`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'output_uuid' in params:
            path_params['output_UUID'] = params['output_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/{output_UUID}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RenderQueueItem',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_application_render_queue_item(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Delete  # noqa: E501

        Remove the Item with UUID from the Render Queue. Returns an error is the item is not found in the queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_application_render_queue_item(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_application_render_queue_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_application_render_queue_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
            return data

    def delete_application_render_queue_item_with_http_info(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Delete  # noqa: E501

        Remove the Item with UUID from the Render Queue. Returns an error is the item is not found in the queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_application_render_queue_item_with_http_info(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_application_render_queue_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_uuid' is set
        if ('output_uuid' not in params or
                params['output_uuid'] is None):
            raise ValueError("Missing the required parameter `output_uuid` when calling `delete_application_render_queue_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'output_uuid' in params:
            path_params['output_UUID'] = params['output_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/{output_UUID}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_player_enter_shot(self, shot_uuid, **kwargs):  # noqa: E501
        """Player Enter Shot  # noqa: E501

        Enter the player with the Shot with UUID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_enter_shot(shot_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid shot_uuid: Shot UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_player_enter_shot_with_http_info(shot_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.do_application_player_enter_shot_with_http_info(shot_uuid, **kwargs)  # noqa: E501
            return data

    def do_application_player_enter_shot_with_http_info(self, shot_uuid, **kwargs):  # noqa: E501
        """Player Enter Shot  # noqa: E501

        Enter the player with the Shot with UUID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_enter_shot_with_http_info(shot_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid shot_uuid: Shot UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['shot_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_player_enter_shot" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'shot_uuid' is set
        if ('shot_uuid' not in params or
                params['shot_uuid'] is None):
            raise ValueError("Missing the required parameter `shot_uuid` when calling `do_application_player_enter_shot`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'shot_uuid' in params:
            path_params['shot_UUID'] = params['shot_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/player/entershot/{shot_UUID}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_player_enter_slot(self, slot_idx, **kwargs):  # noqa: E501
        """Player Enter Slot  # noqa: E501

        Enter the player with the Slot with Index in the current Construct.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_enter_slot(slot_idx, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid slot_idx: Slot index (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_player_enter_slot_with_http_info(slot_idx, **kwargs)  # noqa: E501
        else:
            (data) = self.do_application_player_enter_slot_with_http_info(slot_idx, **kwargs)  # noqa: E501
            return data

    def do_application_player_enter_slot_with_http_info(self, slot_idx, **kwargs):  # noqa: E501
        """Player Enter Slot  # noqa: E501

        Enter the player with the Slot with Index in the current Construct.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_enter_slot_with_http_info(slot_idx, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid slot_idx: Slot index (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['slot_idx']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_player_enter_slot" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'slot_idx' is set
        if ('slot_idx' not in params or
                params['slot_idx'] is None):
            raise ValueError("Missing the required parameter `slot_idx` when calling `do_application_player_enter_slot`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'slot_idx' in params:
            path_params['slot_IDX'] = params['slot_idx']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/player/enterslot/{slot_IDX}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_player_enter_timeline(self, construct_uuid, **kwargs):  # noqa: E501
        """Player Enter Timeline (CID)  # noqa: E501

        Enter the player with the Construct\\Timeline with UUID (CID).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_enter_timeline(construct_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid construct_uuid: Construct UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_player_enter_timeline_with_http_info(construct_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.do_application_player_enter_timeline_with_http_info(construct_uuid, **kwargs)  # noqa: E501
            return data

    def do_application_player_enter_timeline_with_http_info(self, construct_uuid, **kwargs):  # noqa: E501
        """Player Enter Timeline (CID)  # noqa: E501

        Enter the player with the Construct\\Timeline with UUID (CID).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_enter_timeline_with_http_info(construct_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid construct_uuid: Construct UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['construct_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_player_enter_timeline" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'construct_uuid' is set
        if ('construct_uuid' not in params or
                params['construct_uuid'] is None):
            raise ValueError("Missing the required parameter `construct_uuid` when calling `do_application_player_enter_timeline`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'construct_uuid' in params:
            path_params['construct_UUID'] = params['construct_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/player/entertimeline/{construct_UUID}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_player_enter_timeline_current(self, **kwargs):  # noqa: E501
        """Player Enter Timeline (CC)  # noqa: E501

        Enter the player with the current Timeline/Construct (CC)  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_enter_timeline_current(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_player_enter_timeline_current_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.do_application_player_enter_timeline_current_with_http_info(**kwargs)  # noqa: E501
            return data

    def do_application_player_enter_timeline_current_with_http_info(self, **kwargs):  # noqa: E501
        """Player Enter Timeline (CC)  # noqa: E501

        Enter the player with the current Timeline/Construct (CC)  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_enter_timeline_current_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_player_enter_timeline_current" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/player/entertimeline', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_player_exit(self, **kwargs):  # noqa: E501
        """Player Exit  # noqa: E501

        Exit the player and return to the current Construct menu.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_exit(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_player_exit_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.do_application_player_exit_with_http_info(**kwargs)  # noqa: E501
            return data

    def do_application_player_exit_with_http_info(self, **kwargs):  # noqa: E501
        """Player Exit  # noqa: E501

        Exit the player and return to the current Construct menu.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_player_exit_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_player_exit" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/player/exit', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_project_enter(self, project_id, **kwargs):  # noqa: E501
        """Project Enter  # noqa: E501

        Enter the project specified by name. When another project is currently loaded, it is first unloaded.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_project_enter(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: Project name (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_project_enter_with_http_info(project_id, **kwargs)  # noqa: E501
        else:
            (data) = self.do_application_project_enter_with_http_info(project_id, **kwargs)  # noqa: E501
            return data

    def do_application_project_enter_with_http_info(self, project_id, **kwargs):  # noqa: E501
        """Project Enter  # noqa: E501

        Enter the project specified by name. When another project is currently loaded, it is first unloaded.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_project_enter_with_http_info(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: Project name (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_project_enter" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `do_application_project_enter`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['projectID'] = params['project_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/project/enter/{projectID}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_project_exit(self, **kwargs):  # noqa: E501
        """Project Exit  # noqa: E501

        Exit the currently loaded project.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_project_exit(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_project_exit_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.do_application_project_exit_with_http_info(**kwargs)  # noqa: E501
            return data

    def do_application_project_exit_with_http_info(self, **kwargs):  # noqa: E501
        """Project Exit  # noqa: E501

        Exit the currently loaded project.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_project_exit_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_project_exit" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/project/exit', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_render_delete_media_item(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Delete Media  # noqa: E501

        Delete the media of the Queue Item with UUID. Returns an error when the node is not present in the Queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_delete_media_item(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_render_delete_media_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.do_application_render_delete_media_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
            return data

    def do_application_render_delete_media_item_with_http_info(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Delete Media  # noqa: E501

        Delete the media of the Queue Item with UUID. Returns an error when the node is not present in the Queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_delete_media_item_with_http_info(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_render_delete_media_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_uuid' is set
        if ('output_uuid' not in params or
                params['output_uuid'] is None):
            raise ValueError("Missing the required parameter `output_uuid` when calling `do_application_render_delete_media_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'output_uuid' in params:
            path_params['output_UUID'] = params['output_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/deletemedia/{output_UUID}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_render_snapshot(self, body, **kwargs):  # noqa: E501
        """Render Snapshot  # noqa: E501

        Generate an image from the Shot with UUID at the specified frame postion, using the default snapshot format settings.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_snapshot(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ImageSnapshot body: json with the Shot UUID, frame position and render path (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_render_snapshot_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.do_application_render_snapshot_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def do_application_render_snapshot_with_http_info(self, body, **kwargs):  # noqa: E501
        """Render Snapshot  # noqa: E501

        Generate an image from the Shot with UUID at the specified frame postion, using the default snapshot format settings.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_snapshot_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ImageSnapshot body: json with the Shot UUID, frame position and render path (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_render_snapshot" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `do_application_render_snapshot`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['image/jpeg', 'application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/tools/image', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_render_start(self, **kwargs):  # noqa: E501
        """Render Queue Start  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_start(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DeleteMediaData body: Start processing the render queue. If delete_existing_media is true, existing media will be deleted before rendering.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_render_start_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.do_application_render_start_with_http_info(**kwargs)  # noqa: E501
            return data

    def do_application_render_start_with_http_info(self, **kwargs):  # noqa: E501
        """Render Queue Start  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_start_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DeleteMediaData body: Start processing the render queue. If delete_existing_media is true, existing media will be deleted before rendering.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_render_start" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/start', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_render_stop(self, **kwargs):  # noqa: E501
        """Render Queue Stop  # noqa: E501

        Stop rendering all queue items.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_stop(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_render_stop_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.do_application_render_stop_with_http_info(**kwargs)  # noqa: E501
            return data

    def do_application_render_stop_with_http_info(self, **kwargs):  # noqa: E501
        """Render Queue Stop  # noqa: E501

        Stop rendering all queue items.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_stop_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_render_stop" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/stop', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_render_stop_item(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Stop  # noqa: E501

        Stop rendering the Queue Item with UUID. Returns an error when the node is not present in the Queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_stop_item(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_render_stop_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.do_application_render_stop_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
            return data

    def do_application_render_stop_item_with_http_info(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Stop  # noqa: E501

        Stop rendering the Queue Item with UUID. Returns an error when the node is not present in the Queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_render_stop_item_with_http_info(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_render_stop_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_uuid' is set
        if ('output_uuid' not in params or
                params['output_uuid'] is None):
            raise ValueError("Missing the required parameter `output_uuid` when calling `do_application_render_stop_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'output_uuid' in params:
            path_params['output_UUID'] = params['output_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/stop/{output_UUID}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_restart(self, **kwargs):  # noqa: E501
        """Application Restart  # noqa: E501

        Restart the application (Windows only).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_restart(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_restart_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.do_application_restart_with_http_info(**kwargs)  # noqa: E501
            return data

    def do_application_restart_with_http_info(self, **kwargs):  # noqa: E501
        """Application Restart  # noqa: E501

        Restart the application (Windows only).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_restart_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_restart" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/restart', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def do_application_shutdown(self, **kwargs):  # noqa: E501
        """Application Shutdown  # noqa: E501

        Shutdown the application.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_shutdown(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.do_application_shutdown_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.do_application_shutdown_with_http_info(**kwargs)  # noqa: E501
            return data

    def do_application_shutdown_with_http_info(self, **kwargs):  # noqa: E501
        """Application Shutdown  # noqa: E501

        Shutdown the application.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.do_application_shutdown_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method do_application_shutdown" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/shutdown', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_application_player_playmode(self, **kwargs):  # noqa: E501
        """Player Get Mode  # noqa: E501

        Get the current Player mode. Returns an error when not in the Player.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_application_player_playmode(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: PlaymodeData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_application_player_playmode_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_application_player_playmode_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_application_player_playmode_with_http_info(self, **kwargs):  # noqa: E501
        """Player Get Mode  # noqa: E501

        Get the current Player mode. Returns an error when not in the Player.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_application_player_playmode_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: PlaymodeData
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_application_player_playmode" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/player/playmode', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PlaymodeData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_application_render_queue(self, **kwargs):  # noqa: E501
        """Render Queue List  # noqa: E501

        List all current Items in the Render Queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_application_render_queue(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: RenderQueueList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_application_render_queue_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_application_render_queue_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_application_render_queue_with_http_info(self, **kwargs):  # noqa: E501
        """Render Queue List  # noqa: E501

        List all current Items in the Render Queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_application_render_queue_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: RenderQueueList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_application_render_queue" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RenderQueueList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_application_render_queue_item(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Get  # noqa: E501

        Get the status of the Queue Item with UUID. Returns an error is the item is not present in the Render Queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_application_render_queue_item(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: RenderQueueItem
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_application_render_queue_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.get_application_render_queue_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
            return data

    def get_application_render_queue_item_with_http_info(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Get  # noqa: E501

        Get the status of the Queue Item with UUID. Returns an error is the item is not present in the Render Queue.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_application_render_queue_item_with_http_info(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :return: RenderQueueItem
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_application_render_queue_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_uuid' is set
        if ('output_uuid' not in params or
                params['output_uuid'] is None):
            raise ValueError("Missing the required parameter `output_uuid` when calling `get_application_render_queue_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'output_uuid' in params:
            path_params['output_UUID'] = params['output_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/{output_UUID}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RenderQueueItem',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_application_state(self, **kwargs):  # noqa: E501
        """Application Status  # noqa: E501

        Get the state of the application  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_application_state(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: ApplicationData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_application_state_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_application_state_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_application_state_with_http_info(self, **kwargs):  # noqa: E501
        """Application Status  # noqa: E501

        Get the state of the application  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_application_state_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: ApplicationData
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_application_state" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApplicationData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_application_render_start_item(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Start  # noqa: E501

        Start processing the Queue Item with UUID. If delete_existing_media is true, existing media will be deleted before rendering. Returns an error if the UUID does not references a valid output node.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_application_render_start_item(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :param DeleteMediaData body: json with delete_existing_media boolean
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_application_render_start_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.post_application_render_start_item_with_http_info(output_uuid, **kwargs)  # noqa: E501
            return data

    def post_application_render_start_item_with_http_info(self, output_uuid, **kwargs):  # noqa: E501
        """Render Queue Item Start  # noqa: E501

        Start processing the Queue Item with UUID. If delete_existing_media is true, existing media will be deleted before rendering. Returns an error if the UUID does not references a valid output node.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_application_render_start_item_with_http_info(output_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Uuid output_uuid: Output node UUID (required)
        :param DeleteMediaData body: json with delete_existing_media boolean
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_uuid', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_application_render_start_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_uuid' is set
        if ('output_uuid' not in params or
                params['output_uuid'] is None):
            raise ValueError("Missing the required parameter `output_uuid` when calling `post_application_render_start_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'output_uuid' in params:
            path_params['output_UUID'] = params['output_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/render/start/{output_UUID}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def set_application_player_playmode(self, body, **kwargs):  # noqa: E501
        """Player Set Mode  # noqa: E501

        Set the current Player mode. Returns an error when not in the Player.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_application_player_playmode(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PlaymodeData body: json with playmode data (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.set_application_player_playmode_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.set_application_player_playmode_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def set_application_player_playmode_with_http_info(self, body, **kwargs):  # noqa: E501
        """Player Set Mode  # noqa: E501

        Set the current Player mode. Returns an error when not in the Player.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_application_player_playmode_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PlaymodeData body: json with playmode data (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method set_application_player_playmode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `set_application_player_playmode`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/application/player/playmode', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
